### ISSUE TITLE
Missing Environment Variable for DB Table Prefix

### ISSUE THREAD

**Issue by kjprince** [roots/bedrock#140]
I just whipped up a new project and the environment variable for the db table prefix was missing ( `WP_TABLEPREFIX=wp_` ).

I started a new project early last week and it was there as I expected. 

Not sure if this is a bug, but worth mentioning.

**Comment by swalkinshaw** [comment]
We set a default to `wp_` if `DB_PREFIX` env var isn't set: https://github.com/roots/bedrock/blob/43b734afbecb54b882fafe923dba7960529e2275/config/application.php#L38

Make sure that line is in your config.

**Comment by kjprince** [comment]
That line is of course there, what I'm referring to is the default setup after creating a new project with Composer, I have to add the environment variable manually as it's not created in the `.env` file after the initial project creation.

**Comment by etcook** [comment]
@kjprince That's why the default is there - to capture those instances when it isn't in the .env file. Most people just leave it be. I don't think every "flag" should need to be explicitly defined, especially those used less often.
