### ISSUE TITLE
Repetition of code in config/environments files. 

### ISSUE THREAD

**Issue by mrobit** [roots/bedrock#143]
There's a little bit of code repetition going on in the environment PHP files. It's not much but it's just something I'm curious about.

Dotenv is setting `$_ENV`, `putenv`, etc. automatically for everything in `.env`, and then the `define` calls are being called in the environment PHP files, but it's the same code in each of the files. This could be reduced down to something like this:

```php
Dotenv::required(array('DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL'));

/**
 * Use $_ENV variables set within Dotenv to create our definitions.
 */
foreach ($_ENV as $key => $value) {
  if (! defined($key)) {
    define($key, $value);
  }
}

if (! defined('DB_HOST')) {
  define('DB_HOST', 'localhost');
}
```

For any definitions that need to have a default that aren't required by Dotenv, they could just be set by checking whether they are `defined()` or not, like the `defined('DB_HOST');` bit in the code. Thoughts? Like I said, it's just a little bit of code repetition, and there is still place for those environment PHP files since there are other definitions that would be constant across installs, no matter what, so there's no need to get rid of them entirely. It just seems like a little bit of boilerplate could be removed.

**Comment by swalkinshaw** [comment]
I'll probably think more about this, but for now my one thought is that is reduces "grepability" a bit since you'd no longer have any explicit code with it being set.

**Comment by QWp6t** [comment]
I don't think it's a very good idea to set every single environment variable as a global constant like that. Instead, only set the variables that interest you.

```php
$envars = array('DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL');
Dotenv::required($envars);

foreach ($envars as $key => $value) {
  // ...
}
```

**Comment by swalkinshaw** [comment]
Going to pass on this idea @mrobit but thanks for bringing it up. I'd rather have it explicit and clear.

**Comment by mrobit** [comment]
All good! Just wanted to put the idea out there. Thanks for the consideration.
