### ISSUE TITLE
WP database script

### ISSUE THREAD

**Issue by dominiceales** [roots/bedrock#148]
Hi there,

I am looking into Bedrock for a solution to running dev, staging and production versions of WP in a simple way. Also I like the 'WP as a library' idea.

I am confused about my installation - I can't find the SQL install script - is it missing?

Cheers,
Dominic

**Comment by swalkinshaw** [comment]
I'm confused what you mean by "SQL install script". If you could elaborate that would be appreciated.

I'm closing this since it isn't an "issue" but you can still reply.

**Comment by dominiceales** [comment]
Great - you're right it isn't an issue.

When I've installed Wordpress from a zip in the past I remember getting an SQL script to install into the database that WP uses. I must be missing something obvious if this makes no sense to you.

Any idea what I mean?

**Comment by swalkinshaw** [comment]
WordPress takes care of this during it's install process. You need to create the database first but it will create all the tables. Once the site is setup you just go to http://example.com/wp and WP will take over from there.

**Comment by dominiceales** [comment]
Ok thanks. 

My problem was enhanced because I changed the name of the wp directory in the composer.json and in .env - but it seems something was still lost and it wasn't finding the install script.

Thanks for your help.

**Comment by QWp6t** [comment]
@dominiceales you have to change it in the bottom of `application.php` as well. Also, if you use wp-cli, then make sure you change it in `wp-cli.yml`.

**Comment by dominiceales** [comment]
Thanks @QWp6t 

I also found one more place to change it - in web/index.php.
