### ISSUE TITLE
WP-CLI and multisite

### ISSUE THREAD

**Issue by soifou** [roots/bedrock#149]
Hi, I'm having trouble to use wp-cli when multisite is enabled on Bedrock.

When these constants are defined in config/environment or config/application.php
```
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
```
wp-cli does not return anything on the prompt (no error, nothing). 
But if MULTISITE is set to false, wp-cli is ok.

This behaviour does not appear on a standard Wordpress multisite.
 
Anyone else have experienced these issue ?

**Comment by etcook** [comment]
I don't believe this is a bedrock issue. When you're on multisite, try setting the url to explicitly declare which blog you're connecting to.

http://wp-cli.org/config/

`wp --url=<url>`

**Comment by soifou** [comment]
OMG you're so right, I forgot to read this part of the doc... everything works indeed. 
Thanks and sorry for this one !

**Comment by austinpray** [comment]
@etcook :sunglasses:

**Comment by etcook** [comment]
@soifou I just know because I've been bitten by the same issue. WP CLI error output is not very helpful.
