### ISSUE TITLE
Move Capistrano deployment configs to a separate repo

### ISSUE THREAD

**Issue by retlehs** [roots/bedrock#157]

**Comment by austenc** [comment]
I see this is either in process or already done. Would it be possible to create a repo with rocketeer configs as well? I'm happy to create one in my account that you can be copied over if you'd like? Willing to help with this however I can!

**Comment by swalkinshaw** [comment]
@austenc right now I'd be willing to add a link to it in the `README` (or start a Wiki page on deploys and link that too).

At some point we might be open to moving it under our org but I don't want to commit to supporting just yet since none of us use it.

**Comment by swalkinshaw** [comment]
Closed by https://github.com/roots/bedrock/pull/163

**Comment by austenc** [comment]
Awesome, thanks @swalkinshaw. I like capistrano, but a full composer / php is just easier for me! I'll let you know when I've put something up, cheers!
