### ISSUE TITLE
different env for theme

### ISSUE THREAD

**Issue by padalec** [roots/bedrock#160]
Hi there,
grate work!! When I start use badrock I just love it! I have a little question how can I configure a DB env. for different theme? I need this because I have different db for theme. Example below: 
<pre>
theme1
DB_NAME = theme1
DB_USER = user_theme1
DB_PASSWORD=''
DB_HOST='localhost'
DB_PREFIX ='theme1__'
theme2
DB_NAME = theme2
DB_USER = user_theme2
DB_PASSWORD=''
DB_HOST='localhost'
DB_PREFIX ='theme2__'
</pre>

I try to create a new config\environments theme1.php but DB_PREFIX doesn't work.

Regards

**Comment by retlehs** [comment]
please open a thread on https://discourse.roots.io/
