### ISSUE TITLE
Redirect loop on php built-in server

### ISSUE THREAD

**Issue by Soullivaneuh** [roots/bedrock#161]
I try to run your bedrock solution with the built-in php server on development env.

My .env file:

```
DB_NAME=test
DB_USER=root
DB_PASSWORD=
DB_HOST=localhost

WP_ENV=development
WP_HOME=http://localhost:8000/
WP_SITEURL=http://localhost:8000/wp/
AUTH_KEY='xxxx'
SECURE_AUTH_KEY='xxxx'
LOGGED_IN_KEY='xxxx'
SECURE_AUTH_SALT='xxxx'
LOGGED_IN_SALT='xxxx'
NONCE_SALT='xxxx'
```

And the server command:

```sh
php -S localhost:8000 web/index.php 
```

If I go on `http://localhost:8000/wp`, I'm having a redirect loop on install.php.

If I try `http://localhost:8000`, I'm simply redirected on `http://localhost` (apache) for no reason.

Can you reproduce the issue?

Tip: Have a foreman / built-in dev server solution could be a nice addition. :+1:

**Comment by Soullivaneuh** [comment]
Ok found why. Just add the `-t` option to specify root directory:

```sh
php -S localhost:8000 -t web
```

Are you interested for a PR managing built-in server and foreman?

Thanks.

**Comment by swalkinshaw** [comment]
The built-in server is awesome for quick stuff but we try and recommend dev/prod parity by using the same web server across environments (see https://github.com/roots/bedrock-ansible).

I'd like to get the Wiki going with some topics so that would be a good place to document this.

And thanks for posting the solution :+1:

**Comment by joshuairl** [comment]
I'm actually just getting a white screen.
Running from php -S 0.0.0.0:8000 -t web it just returns white screen. Any tips?

**Comment by Soullivaneuh** [comment]
@joshuairl Seems to be another error.

Have you any log? You better ask your question here to get support I think: https://discourse.roots.io/c/bedrock :+1:
