### ISSUE TITLE
Keeping customer Wordpress up to date on git

### ISSUE THREAD

**Issue by MaximeDevalland** [roots/bedrock#162]
Let's say I use the bedrock stack.
I manage all my WP and plugins with composer, and the project is hosted on git.
Everything is fine, except that if someone adds a plugin from the wp-admin, it won't be added to my composer.json and also this change won't be committed in git.

How do you manage this use case?

Thanks

**Comment by retlehs** [comment]
https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md#using-the-issue-tracker

> Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/)).

**Comment by M13Kd** [comment]
God Bless America

**Comment by M13Kd** [comment]
Thanks again for remembering me folks.
