### ISSUE TITLE
Problem with docker linked containers

### ISSUE THREAD

**Issue by lautreamont3** [roots/bedrock#166]
There is a problem with bedrock and docker, if you use separate container for database. Docker service that enable linking process insert in bedrock container WP_NAME from db container that phpdotenv.getenv pickup (mysql or mariaDB). Only solution, that I find in short time, is to change DB_NAME to something else in .env and application.php.

**Comment by swalkinshaw** [comment]
I'd rather not change `DB_NAME` since it matches up with the WP constant for consistency.

Is this actually a default built into Docker or just some 3rd party Docker image/Dockerfile?

**Comment by etcook** [comment]
@swalkinshaw DB_NAME is a custom env variable.

**Comment by lautreamont3** [comment]
It's not custom built. Try official mysql or mariadb and you get DB_NAME in your link-ed container.

**Comment by etcook** [comment]
@lautreamont3 Those are custom built images. There is no official convention that's mandated by Docker. If those image authors choose to use the DB_NAME convention, it is of their own accord, no different than Bedrock's usage choice.

**Comment by lautreamont3** [comment]
I understand what you are saying but many people just pull mysql from "official" repository and work with it. If you do that you have problem.

**Comment by etcook** [comment]
@lautreamont3 I think it would be difficult to account for every permutation or naming convention unless you are advocating namespacing. If that's the case, shouldn't the mysql or mariadb images be namespaced? Also, isn't the db_name the one you're using anyways?

**Comment by lautreamont3** [comment]
I am really soory, its my mistake and ignorance. I know that it was not in mysql-docker-built-scripts because I was study them and know that its docker mechanism, but I, obviusly, did not understand mechanism enough. That envionment variable is build by container linking process and use simbolic name witch user specify on start of linking container. Its alias for connection. Option is something like ```--link container:alias```. I used ```db``` for alias and inside linking container get ```DB_NAME``` when I, eventually, used ```mariadb``` I got ```MARIADB_NAME```.

**Comment by ghostal** [comment]
Good detective work on this, saved me what I can only imagine would have been an annoying amount of time!

To clarify, the issue arises from having a docker container with the alias `db`. This means any container linked to it has an environment variable set called `DB_NAME` containing the fully qualified container name, which obviously conflicts with the `.env` file.

One solution, as described above, is to simply alias your docker database container something else (e.g. `database`, `mysql`, etc).

However, these environment variables are only created when using the version 1 of the `docker-compose.yml` file format (as stated [here](https://docs.docker.com/compose/link-env-deprecated/)). Upgrading your `docker-compose.yml` file to version 2 or higher of the format means you won't have the issue any more - you can still alias your database container `db` :tada: :smile:
