### ISSUE TITLE
Concat JS and CSS Wordpress Plugins

### ISSUE THREAD

**Issue by faoliveira** [roots/bedrock#172]
Well, like any Wordpress, installing plugins makes means to lose control which CSS and JS are loaded (unless you make a deregister the functions.php for each, that i know or use another plugin for concat). Looking for something that uses less CPU in VPS for concat these JS and CSS files, i arrived at that https://github.com/Automattic/nginx-http-concat. But with Bedrock returns me that: 

`<link rel="stylesheet" href="http://domain.com/wp/_static/??/wp-includes/css/dashicons.min.css,/wp-includes/css/admin-bar.min.css?m=1430154973j">`

Not working well

**Comment by swalkinshaw** [comment]
This isn't really an issue with Bedrock itself. That plugin seems to make assumptions about the type of WordPress install you have.

It seems like it wouldn't work with any WP subdirectory install and not just Bedrock specifically.
