### ISSUE TITLE
Vulnerabilities in files/packages not maintained by Composer

### ISSUE THREAD

**Issue by kalenjohnson** [roots/bedrock#175]
In light of the [recent vulnerabilities](https://blog.sucuri.net/2015/05/jetpack-and-twentyfifteen-vulnerable-to-dom-based-xss.html) in Genericons which affected both Jetpack and the Twenty-Fifteen theme, I think we should re-examine what gets loaded via Composer.

[This post](https://discourse.roots.io/t/twenty-fifteen-genericons/3717) on Discourse highlights a rather serious hole - themes installed with WordPress cannot be updated with Bedrock. At least not on staging or production. But unless WordPress releases a point release with the updated Twenty Fifteen theme, it's actually impossible to correctly update the theme unless you do it manually. And if you ever deploy or run `composer update` again, there is the possibility that the vulnerable theme can be installed again.

Any stock themes that the user actually wants should be installed via Composer in the normal way. Then at least they can be updated properly.

In my mind, there's two options:

1. Revert back to creating a Composer repository that points to the no-content.zip file of WP.
2. After a `composer install` or `update`, using one of the post install hooks and deleting all folders in `web/wp/wp-content/themes`.

Open to discussion

**Comment by swalkinshaw** [comment]
This is the responsibility of WordPress to release new versions. If a bundled theme contains a vulnerability then they need to fix that.

People can always manually apply fixes until then.
