### ISSUE TITLE
.htaccess rewrite for the /web subdirectory

### ISSUE THREAD

**Issue by royduin** [roots/bedrock#180]
Hi,

The current Bedrock setup is not ideal for shared hosting environments or hosting environments with a control panel like Direct Admin. Changing the vhost to point to the `/web` directory is not always possible, allowed or the best option. Maybe it's an idea to ship a `.htaccess` file with Bedrock with some rewrites like suggested here: https://discourse.roots.io/t/ftp-use-and-point-domain-to-web-folder-w-htaccess/1556 to make Bedrock more "compatible". But with some extra security like:
```
RewriteRule .env - [F]
```
OR
```
Order Deny,Allow
deny from all

<Files web/*>
    allow from all
</Files>
```

Maybe we can debate here for the best `.htaccess` setup?

**Comment by hyyan** [comment]
@royduin Hey , I agree with you bedrock should explain how it could ships with shared hosting environments , I faced this before , and here is my solution after digging using the following .htacces file : 


```
Options -Indexes
# .htaccess primary domain to web redirect
# this file must be in the (public_html | web ) folder of your hosting account 
# make the changes to the file according to the instructions.

<IfModule mod_rewrite.c>
    # Do not change this line.
    RewriteEngine on

    # Change %host% to be your primary domain.
    RewriteCond %{HTTP_HOST} ^(www.)?%host%$

    # Change 'web' to be the folder you will use for your primary domain.
    RewriteCond %{REQUEST_URI} !^/web/

    #********************
    # NOT RRCOMMENDED   *
    #********************
    #
    # Uncomment those two lines if you want dirs and files to be accessible out of the
    # your primary domain dir.

    #RewriteCond %{REQUEST_FILENAME} !-f 
    #RewriteCond %{REQUEST_FILENAME} !-d

    # Change 'web' to be the folder you will use for your primary domain.
    RewriteRule ^(.*)$ /web/$1

    # Change %host% to be your primary domain again. 
    # Change 'web' to be the folder you will use for your primary domain 
    # followed by / then the main file for your site, index.php, index.html, etc.
    RewriteCond %{HTTP_HOST} ^(www.)?%host%$ 
    RewriteRule ^(/)?$ web/index.php [L]
</IfModule>
```

**Comment by royduin** [comment]
@hyyan, that's a nice and clean solution. Just rewrite everything and don't allow file access in the root directory! @swalkinshaw: maybe you can make this part of the Bedrock project?

**Comment by hyyan** [comment]
@royduin glade you liked the solution , but I think it is not a good idea to make that part of the Bedrock project so we can still use it with none shared hosting envs , but I think it will be good a idea if such a solution can be mentioned in the bedorck documentaion  @swalkinshaw ?

**Comment by royduin** [comment]
@hyyan, why not make it part of the Bedrock project? It makes it just better compatible, for people who are currently using the `/web` directory nothing changes because the `.htaccess` file will not be executed (it's outside the document root in that case).

Maybe we can make the `.htaccess` more generic? The domainname inside is not ideal.

**Comment by hyyan** [comment]
@royduin you are correct , while it won't harm but it would ask the server for unnecessary extra work (redirecting) to do .

`make the .htaccess more generic? The domainname inside is not ideal.` ? any suggestion about that ?

**Comment by royduin** [comment]
@hyyan, if your document root is currently set to the `/web` directory and you place your `.htaccess` in the root it will not be executed so it doesn't take any unnecessary resources.

I'm going to experiment with the `.htaccess` to make it more generic, I'll come back on that.

**Comment by hyyan** [comment]
@royduin You are totally write about that , God how I've missed that ,sorry :blush:

**Comment by Foxaii** [comment]
It's been a while since I've had to do this. But you can rework Bedrock's folder structure quite easily.
Usually you only need to edit the following references:

https://github.com/roots/bedrock/blob/master/config/application.php#L3
https://github.com/roots/bedrock/blob/master/web/wp-config.php#L7-L8

**Comment by royduin** [comment]
@Foxaii, you're right (but your missing this one: https://github.com/roots/bedrock/blob/master/composer.json#L50-L54), but that's not that safe... that way the `.env` files are accessible.

**Comment by Foxaii** [comment]
Thanks for pointing to the `composer.json` changes.

All the shared hosts that I've been forced to use allow access above the web root. So you would have a structure like follows:

```
├── bedrock      # Config folder with .env above the web root and is only accessible on the server.
└── public_html  # public_html becomes your web folder and is moved outside the bedrock config.
```

You can also run other bedrock installs (subdomains, addon domains etc) :

```
├── bedrock           # Config folder with .env above the web root and is only accessible on the server.
├── subdomain_bedrock # Subdomain config folder
└── public_html       # public_html becomes your web folder and is moved outside the bedrock config.
       └─ subdomain   # subdomain becomes your web folder for the subdomain_bedrock config.
```

**Comment by royduin** [comment]
@Foxaii, that's a possibility but it's much easier to have a `.htaccess` file in the root that handles the sub-directory structure. That way I can clone Bedrock, just change the `composer.json` file to my needs (plugins from wpackagist.org and a theme from a private repo), push it to my own project repo and do a `git clone` in my `public_html` directory on a shared hosting account.

So, why not include a `.htaccess` file that handles this in Bedrock?

**Comment by Foxaii** [comment]
Easier isn't always better. Generally speaking, .htaccess files are bad for performance and your solution puts the .env file in the web root, which poses a security issue if anything compromises the .htaccess file (such as overrides being disallowed).

**Comment by etcook** [comment]
Agreed. Not to mention, environmental specific configuration, especially to this level, shouldn't be automatically included.

**Comment by MikeiLL** [comment]
It seems like most web devs will be moving from Shared to VPS hosting, since VPS is so affordable and package management is making it "very easy" to configure a server. But in the meantime I certainly look forward to whatever insights and tools can me made available for Bedrock-style deployment in a shared environment.

**Comment by retlehs** [comment]
> The current Bedrock setup is not ideal for shared hosting environments or hosting environments with a control panel like Direct Admin

sounds like a non-ideal hosting setup

> Changing the vhost to point to the /web directory is not always possible, allowed or the best option.

bedrock might not be the best fit for production if you're on a non-ideal hosting setup

> Maybe it's an idea to ship a .htaccess file with Bedrock

bedrock will never ship with a `.htaccess` file. this can be covered in docs, but that'll be about it.

**Comment by royduin** [comment]
Thanks for all the replies! Regrettably it will not be shipped with Bedrock. Maybe I'll fork it and change it to my needs.

Great work!

**Comment by hyyan** [comment]
@royduin I have my own project which called [GWP](https://github.com/hyyan/gwp) the project is completely inspired from bedorck  , with following improvements : 

* Better environment support (with env and php files)
* Phing build (automate the build and deployment process with shared hosts in )

The project does not have a documentation yet , cause it has been used for my own company projects only, and I couldn't find the time to add one , but I am ready to clear things up if you are interested ,it is easy to follow with if you understand how bedrock is organized.

**Comment by austinpray** [comment]
@hyyan https://github.com/hyyan/gwp/blob/00954a330a25488e7d86d56601b3bd2c90729d93/build/build.properties#L22

**Comment by hyyan** [comment]
@austinpray the line define the full path for composer path in windows env , this is because phing does not know how to find composer

**Comment by hyyan** [comment]
@austinpray it is very common to include the composer.phar file in the project dir , so the file can be found anyway

**Comment by hyyan** [comment]
@austinpray , @royduin  If some is interested , I have documented  [GWP](http://hyyan.github.io/gwp)

**Comment by royduin** [comment]
@hyyan, I'll look into it!

**Comment by jordywijman** [comment]
Isn't this a way more clean solution for this issue, you can't really get it more dynamic this way.
Thoughts on this?

```
#  Add directives
RewriteEngine on

#  Change root directory to "web" folder
RewriteCond %{THE_REQUEST} ^GET\ /web/
RewriteRule ^web/(.*) /$1 [L,R=301]
RewriteRule !^web/ web%{REQUEST_URI} [L]
```

**Comment by M13Kd** [comment]
What's up Folk


Sent from my MetroPCS 4G Android device

-------- Original message --------
