### ISSUE TITLE
File structure breaks /wp-admin/ routing

### ISSUE THREAD

**Issue by roosterpark-porch** [roots/bedrock#185]
We've successfully installed and deployed a bedrock instance via the ansible provisioner, however, if you attempt to navigate to:

`http://site.dev/wp-admin/`

you are 302 redirected to:

`http://site.dev/wp/wp-login.php?redirect_to=http%3A%2F%2Fadvice.dev%2Fwp-admin%2F&reauth=1`

After successfully inputting username and password, you are redirected back to the same URL. This loop is unbreakable.

I realize that 'just put /wp/wp-admin' is a valid work around, but this feels like it should be fixed via nginx rewrite rules that do not require knowledge of the file system hierarchy to successfully use the admin tools of the bedrock wordpress stack.

The writing of this url param is accomplished by the `wp_login_url()` function in `general-template.php` which should not be toyed with as it would be overwritten if/when a wordpress upgrade occurred.

**Comment by swalkinshaw** [comment]
Browsing to `/wp/wp-admin` isn't a "workaround". It's just the proper URL.

We might be open to a PR which adds the rewrites but this would be done on https://github.com/roots/bedrock-ansible repo anyway.

**Comment by M13Kd** [comment]
@Swalkinshaw we can append Windows LIVE Sign In as well as the mobile os sdk courtesy of Microsoft and Xbox LIVE.  WORDPRESS FOR XBOX LIVE WOULD BE A GREAT WAY TO START A NEW APP ON XBOX LIVE. HIT ME UP WITH A RESPONSE AND THE WORDPRESS PLUGIN FOR ANDROID IS A GOOD IDEA AS WELL PLEASE CHECK MY REPOSITORIES

**Comment by LABCAT** [comment]
I am actually having the same issue. How can I prevent http://site.dev/wp-admin/ redirecting to the login page?

When people see a login form they expect to be able to login but as pointed out in the first comment logging in (even if the details are correct) just redirects you back to the same link.

**Comment by fab120** [comment]
I do not experience this behavior on any of my websites.

`http://site.dev/wp-admin/` redirects to `http://site.dev/wp/wp-admin/?redirect_to=http://site.dev/wp/wp-admin&reauth=1` that has the correct `redirect_to` parameter.

Anyway if you want to disable `/wp-admin` redirect, you have to remove this [wordpress action](https://github.com/WordPress/WordPress/blob/526f0d01d4cebe54c03f9d05fdb681960c3927b2/wp-includes/default-filters.php#L529) with
```php
remove_action('template_redirect', 'wp_redirect_admin_locations', 1000);
```

**Comment by LABCAT** [comment]
So I did a fresh install and it http://site.dev/wp-admin/ redirects to http://site.dev/wp/wp-admin/?redirect_to=http://site.dev/wp/wp-admin&reauth=1 as suggested by fab120.

Looked at my apache config for the sites where it wasn't working and noticed it was incorrect. Updated to match the apache config outlined here:
https://roots.io/docs/bedrock/master/server-configuration/#apache-configuration-for-bedrock

If anyone else experiences this issue I recommend double checking your apache configuration file.
