### ISSUE TITLE
Images on Multisite Subdirectory Install

### ISSUE THREAD

**Issue by tgelles** [roots/bedrock#187]
Images on my multisite 404/are broken when their url is similar to the standard install. E.g.:

*http://example.dev/site-1/app/uploads/sites/1/...*
*http://example.dev/site-2/app/uploads/sites/2/...*

But when I remove the site directory (**site-1**, **site-2**) from the image url (thus changing it to *example.dev/app/uploads/sites/1/...*) the images load. 

Has anyone else encountered this? What was your solution? Was it just editing the database for each and every site? Did you edit the .htaccess or a config .php file?

**Comment by retlehs** [comment]
please use https://discourse.roots.io/ for personal support requests, not this issue tracker ([as stated in the contributing guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md#using-the-issue-tracker))
