### ISSUE TITLE
SSH to VM timeout

### ISSUE THREAD

**Issue by zamber** [roots/bedrock#188]
OS: Arch, regular WiFi connection to a DHCP broadband router, nothing fancy.
Port forwarding works, everything in the network and NAT is pingable from the host and the client VM.

Provisioning fails, vagrant ssh fails silently. Debug here https://gist.github.com/zamber/e994dc827fd2bbbb8ffa (ignore paths, I substituted client dirs). This is extremely confusing behavior and can derail people easily.
After a day of investigation and double-checking I stumbled upon `UseDNS no` for fixing timeouts with SSH but it has to be set in `sshd_config` for the client VM.

`UseDNS` is just a [hindrance](https://unix.stackexchange.com/questions/56941/what-is-the-point-of-sshd-usedns-option) at this point and there's [talk](https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/424371) about changing the default configuration to `no` either ways.

I suggest setting it for the base box.

**Comment by swalkinshaw** [comment]
Are you talking about bedrock-ansible?

If so this issue belongs over here -> https://github.com/roots/bedrock-ansible
