### ISSUE TITLE
.env error

### ISSUE THREAD

**Issue by hamza765** [roots/bedrock#189]
Hi, I'm trying to install wp through bedrock through wamp on Windows. I have everything setup, except when i try to install WP, i get an error that says it can't identify the contents of my .env file. 

env file settings:
DB_NAME=sslcom
DB_USER=ssldev
DB_PASSWORD=root
DB_HOST=localhost

WP_ENV=development
WP_HOME=http://localhost
WP_SITEURL=http://localhost/wp

and the code i used for the vhost in apache:

<VirtualHost *:80>
    DocumentRoot "C:/wamp/www/web"
    ServerName localhost
</VirtualHost>

Do you see any errors i have missed?

**Comment by swalkinshaw** [comment]
What's the exact error? `.env` file itself seems fine so it might a Windows/WAMP thing but I have no experience with those.

Regardless, not an actual bug so I'm closing this.

**Comment by hamza765** [comment]
Fatal error: Uncaught exception 'RuntimeException' with message 'Required environment variable missing, or value not allowed: 'DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL'' in C:\wamp\www\vendor\vlucas\phpdotenv\src\Dotenv.php on line 106

RuntimeException: Required environment variable missing, or value not allowed: 'DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL' in C:\wamp\www\vendor\vlucas\phpdotenv\src\Dotenv.php on line 106

And sorry, i didn't know how else to get help. Google didn't help much.
