### ISSUE TITLE
"Deprecated: mysql_connect()" error when installing Bedrock

### ISSUE THREAD

**Issue by PanzerKunst** [roots/bedrock#198]
I'm trying to install Bedrock on my local Windows 7 workstation, and I fail miserably.

This is the procedure I've been doing:

1. Cloned the Bedrock project
2. Copied its content in my (empty) "c:/my-project/wordpress" project directory
3. Opened a terminal, cd-ed to "c:/my-project/wordpress", and executed `composer install`. All good.
4. Copied "c:/my-project/wordpress/.env.example" to "c:/my-project/wordpress/.env", and edited it to the following:

        DB_NAME=<MY_WP_DB>
        DB_USER=root
        DB_PASSWORD=<PASSWORD_FOR_ROOT>
        DB_HOST=localhost

        WP_ENV=development
        WP_HOME=http://localhost
        WP_SITEURL=http://localhost/wp

5. Updated the Apache HTTPD config file to:

        DocumentRoot "c:/my-project/wordpress/web"
        <Directory "c:/my-project/wordpress/web">
            Options Indexes FollowSymLinks
            AllowOverride FileInfo
            Require all granted
        </Directory>

6. Started Apache HTTPD server
7. In my browser, accessed "http://localhost/wp/wp-admin"
8. Got error "Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in C:\Pro\redesigned-cruited.com-frontend\wordpress\web\wp\wp-includes\wp-db.php on line 1482"

What am I doing wrong?

PS: I just asked [the same question on wordpress.stackexchange][1].

  [1]: http://wordpress.stackexchange.com/posts/199641

**Comment by swalkinshaw** [comment]
Not a Bedrock issue. Your local PHP install is using the mysql extension instead of mysqli or PDO as the error says.

**Comment by PanzerKunst** [comment]
Big thank you, you were totally right. I switched from the "php_mysql" extension to the "php_mysqli" extension and it solved the issue.

I just wonder why this error doesn't appear when I do the exact same thing with vanilla Wordpress...

**Comment by oktalk** [comment]
@PanzerKunst I'm experiencing the same issue as you. Could you please share your solution? I don't know PHP well enough to:

> switch from the "php_mysql" extension to the "php_mysqli"
