### ISSUE TITLE
White screen after setting .env on fresh install

### ISSUE THREAD

**Issue by petterannerwall** [roots/bedrock#199]
Hello!

Really looking forward to trying bedrock out but for some reason i cant get it to work.

Just sat everything up running git clone and then composer install. Tried browsing the URL and got a standard "Wordpress cant connect to database" message, nothing strange. 

But when i configure the variables in the .env file i only get a blank white screen, both at the regular and wp-admin url. Im not particularly new to wordpress but i just can't figure this one out. 

When i remove the .env file i get the same database error message again. It's no trouble connecting to the database since i have multiple other local installations working fine. The web root path is pointed to the "\bedrock\web" folder as instructed. 

The content of my .env is as below

DB_NAME=SageDemo
DB_USER=SageDemo
DB_PASSWORD=xxxxxxxx
DB_HOST=www.xxxxx.com

WP_ENV=development
WP_HOME=http://localhost:1020
WP_SITEURL=http://localhost:1020/wp

If it matters my hosting environment is IIS on windows.

Please help me, would love to try bedrock out this week and if i like it, use it on a client's site that i will be building next week.

**Comment by swalkinshaw** [comment]
If you're getting a blank screen then you're getting a PHP error. You'll need to figure out how to properly display those errors or find your error logs and fix the problem.

Since you don't know the error there's nothing we can do to help unfortunately. Closing since this is a setup issue and not a Bedrock bug.

**Comment by petterannerwall** [comment]
Ok, thanks, totally forgot about php errors. This is the error im getting.

( ! ) Fatal error: Uncaught exception 'RuntimeException' with message 'One or more environment variables failed assertions: DB_NAME is missing' in C:\NotSourceControl\SageDemo\bedrock\vendor\vlucas\phpdotenv\src\Validator.php on line 102
( ! ) RuntimeException: One or more environment variables failed assertions: DB_NAME is missing in C:\NotSourceControl\SageDemo\bedrock\vendor\vlucas\phpdotenv\src\Validator.php on line 102
Call Stack
#	Time	Memory	Function	Location
1	0.0003	138088	{main}( )	...\index.php:0
2	0.0007	139800	require( 'C:\NotSourceControl\SageDemo\bedrock\web\wp\wp-blog-header.php' )	...\index.php:5
3	0.0011	148936	require_once( 'C:\NotSourceControl\SageDemo\bedrock\web\wp\wp-load.php' )	...\wp-blog-header.php:12
4	0.0016	150616	require_once( 'C:\NotSourceControl\SageDemo\bedrock\web\wp-config.php' )	...\wp-load.php:42
5	0.0042	212248	require_once( 'C:\NotSourceControl\SageDemo\bedrock\config\application.php' )	...\wp-config.php:8
6	0.0074	265680	Dotenv\Dotenv->required( )	...\application.php:11
7	0.0080	276680	Dotenv\Validator->__construct( )	...\Dotenv.php:83
8	0.0080	276992	Dotenv\Validator->assertCallback( )	...\Validator.php:44

**Comment by kalenjohnson** [comment]
"One or more environment variables failed assertions: DB_NAME is missing"

Seems pretty obvious.

**Comment by petterannerwall** [comment]
Indeed, but as you can see in the .env i posted above it's there and the .env file is located directly in the bedrock folder.

**Comment by austinpray** [comment]
Debugging and support discussion belongs over at https://discourse.roots.io

**Comment by petterannerwall** [comment]
Thanks and sorry for bothering your here, just posted a topic there. https://discourse.roots.io/t/fresh-bedrock-install-php-error-db-name-missing-in-validator-php/4578

**Comment by petterannerwall** [comment]
Just solved it, leaving a reply here aswell if anyone finds this issue.

The problem for me was not having a blank row at the very top of the .env file. Seems like the first row isn't read for some reason...really strange. Maybe add a blank row to the .env.example to avoid this happening to others?

**Comment by louim** [comment]
@petterannerwall you seems to be using windows. It could be worth it to try running the test units from [php dotenv](https://github.com/vlucas/phpdotenv) and check if they pass. 

I never had the problem you encountered. It could be a Windows related problem, or it could be related specifically to your setup.
