### ISSUE TITLE
application.php throwing parse error

### ISSUE THREAD

**Issue by kiwiot** [roots/bedrock#203]
I was sorting out a new capstrano deploy of a WP site with bedrock and it kept giving me a php parse error.

I tacked down to line #13 of application.php

$dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL']);

Specific error : 

Parse error: syntax error, unexpected '[', expecting ')' in /config/application.php on line 13

fixed this by removing the [] from the line.

Is this because the sever is not running a high enough version of php (server = 5.3.9) ?

**Comment by etcook** [comment]
@kiwiot Yes. You need to be running a newer version of PHP.

http://php.net/manual/en/language.types.array.php

**Comment by kiwiot** [comment]
Thanks for the quick reply
