### ISSUE TITLE
Please add a notice about undefined SALT constants to docs

### ISSUE THREAD

**Issue by COLABORATI** [roots/bedrock#207]
Bedrock does not define Wordpress SALT constants, this might lead to a situation where overly enthusiastic users might find themselves in a situation where they deployed their freshly discovered bedrock stack into the wild without any *KEY and *SALT constants defined - there is no warning about that, in fact the current default allows this quite easily to happen. 

I would like to suggest to put at least a red box warning to the documenation about environment variables that reads something like: 

"Important note: ATM Bedrock does NOT define any Wordpress SALT constants, so before deploying this into the wild you MUST add these to your .env file used in production. You can use this service: https://api.wordpress.org/secret-key/1.1/salt "

Of course the better solution would be to always generate these constants by default as a part of the composer install procedure of bedrock, so that people only reading the first page of docs and then flying fast are safe.

**Comment by retlehs** [comment]
thanks for bringing this up, the salts used to be automatically defined during a composer install script that was removed (see #184) 

we should definitely add a note about salts to both the bedrock readme and docs.

related - [salts in trellis](https://github.com/roots/trellis/blob/4c3984c811fa1041b68f9adf9f8418cae81d08e2/group_vars/production/wordpress_sites.yml#L26-L35)

**Comment by retlehs** [comment]
also: https://github.com/aaemnnosttv/wp-cli-dotenv-command

**Comment by retlehs** [comment]
:rocket:
