### ISSUE TITLE
.env advised not to be used in production

### ISSUE THREAD

**Issue by neutraltone** [roots/bedrock#210]
It mentions the following in the phpdotenv docs:

> "phpdotenv is made for development environments, and generally should not be used in production. In production, the actual environment variables should be set so that there is no overhead of loading the .env file on each request."
_https://github.com/vlucas/phpdotenv#usage-notes_

Yet there doesn't seem to be any reference in managing this in the documentation for bedrock.

**Comment by swalkinshaw** [comment]
We're well aware of that but frankly we don't think it really matters. The original (I believe?) dotenv library was for Ruby https://github.com/bkeepers/dotenv. It also started as development only but you can read more about it on that repo about how it's expanded a bit.

It's more difficult to get proper env vars exposed through a web server to PHP so Dotenv is even more useful in PHP than other languages.

The overhead of loading and parsing a single simple file is negligible when you consider how many files WP loads on every single request.

**Comment by QWp6t** [comment]
Related discussion on Roots Discourse: https://discourse.roots.io/t/is-config-in-the-environment-really-a-good-thing/4590
