### ISSUE TITLE
Bedrock Future ?

### ISSUE THREAD

**Issue by 3KyNoX** [roots/bedrock#213]
Hello there and sorry posting that small post in issues.

I just would like to know if WP using MVC structure could be an interesting thing for Bedrock ?
I see more and more interests too around using WP with most used frameworks like Laravel or Symfony.

Because I'm making a lot of research on that topics, I naturally found Bedrock project.

Thanks for any answer.

Best Regards,

3Ky.

**Comment by retlehs** [comment]
please don't use github issues for support, use https://discourse.roots.io/
