### ISSUE TITLE
HHVM + mysqli

### ISSUE THREAD

**Issue by jonlambert** [roots/bedrock#217]
Hi guys - 

Just built my first site with Bedrock - attempting to deploy to a production server running HHVM 3.10.1. I'm getting this error:
```
Catchable fatal error: Argument 3 to mysqli_real_connect() must be of type ?string, bool given in /app/web/wp/wp-includes/wp-db.php on line 1452
```
Possibly relating to this HHVM issue: https://github.com/facebook/hhvm/issues/1817

I have another vanilla Wordpress website running on this server with the same setup. It's working fine - any ideas what's going wrong?

**Comment by swalkinshaw** [comment]
That file is a WP core file which Bedrock just loads directly. Not exactly sure the cause of this but I can confidently say it's not Bedrock :)
