### ISSUE TITLE
SCRIPT_DEBUG true issue

### ISSUE THREAD

**Issue by moise** [roots/bedrock#218]
Hello,
in a development staging with constant 'SCRIPT_DEBUG' set to true I'had some script load errors, just check the screenshot
<a href='http://postimg.org/image/73aug4s5d/' target='_blank'><img src='http://s8.postimg.org/73aug4s5d/Schermata_2015_11_20_alle_09_58_44.jpg' border='0' alt="Schermata 2015 11 20 alle 09 58 44" /></a>

It seems like WordPress try to load scripts from wp-admin and not from wp-includes

any idea?
thank you

**Comment by retlehs** [comment]
can't reproduce.
