### ISSUE TITLE
DISALLOW_FILE_MODS can break expected functionality of plugins on production

### ISSUE THREAD

**Issue by retlehs** [roots/bedrock#219]
After #127 we set the following in `config/environments/production.php`:

```
define('DISALLOW_FILE_MODS', true);
```

Just ran into an issue where admin menus weren't showing on production even though they were present on dev. After digging around I noticed that it was the use of the `install_plugins` role, example from EDD:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/search?utf8=%E2%9C%93&q=install_plugins

I don't know what other plugins are doing this, but I just ran into this with EDD and some EDD addons. 

Is it safe to assume this should be considered a bug with plugins that do this?

**Comment by austinpray** [comment]
For posterity: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/d02aefe0d5d9b82c70e2a44880d1bafd191897c9/includes/admin/admin-pages.php#L40-L41

**Comment by etcook** [comment]
@retlehs What role should Pip use instead?

**Comment by retlehs** [comment]
@etcook one that isn't `install_plugins`? lol

there's lots of possibilities, it's not my place to pick which one fits best in his plugin

**Comment by etcook** [comment]
@retlehs I'll reach out to Pip on this issue. Thanks, Ben!

**Comment by mAAdhaTTah** [comment]
I don't know, if the menu is to install plugins, and we're deliberately disabling the ability to install plugins, that doesn't seem like a bug to me.

**Comment by etcook** [comment]
@mAAdhaTTah I think that's a good observation. There are two menu items missing, though - the extensions one makes sense, but what about info/tools?

This is only affected on production, right?

**Comment by retlehs** [comment]
the menus/pages i'm talking about in EDD have nothing to do with installing plugins

![image](https://cloud.githubusercontent.com/assets/115911/11349393/a4e7edfc-91f1-11e5-8f47-2400b71e0c30.png)

and the extensions page doesn't try to install the plugins via wp or anything:

![image](https://cloud.githubusercontent.com/assets/115911/11349406/ba2977d0-91f1-11e5-9907-e2003133972a.png)

**Comment by retlehs** [comment]
there are also EDD extensions that are using `install_plugins` to add submenu pages for things that aren't related to installing plugins. eg. the product updates plugin, which is just:

![image](https://cloud.githubusercontent.com/assets/115911/11349436/e39be710-91f1-11e5-8e76-c17171d5d354.png)

**Comment by retlehs** [comment]
>  There are two menu items missing, though - the extensions one makes sense, but what about info/tools?

* two items from EDD core, more in EDD extensions

* no, it doesn't make sense for the extensions one. the purpose of that page is not to install plugins via the wordpress admin.

* yes, info/tools is also missing.

> This is only affected on production, right?

yes, that's the point of this issue

**Comment by retlehs** [comment]
[this plugin](https://github.com/rtCamp/nginx-helper/pull/67) switched from `install_plugins` to `manage_options` for the same reason as this issue (`DISALLOW_FILE_MODS` enabled)

**Comment by mAAdhaTTah** [comment]
Seems to me if you're using `install_plugins` for something other than installing plugins, you're `_doing_it_wrong`.

**Comment by etcook** [comment]
@retlehs and @mAAdhaTTah I think you're right.

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4036

**Comment by etcook** [comment]
@retlehs @mAAdhaTTah https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4036#issuecomment-159112366

**Comment by lukecav** [comment]
This is a related core ticket for plugins restricts should not be set when DISALLOW_FILE_MODS constant is enabled in wp-config.
[https://core.trac.wordpress.org/ticket/25219](url)
