### ISSUE TITLE
Dynamically set WP_HOME and WP_SITEURL

### ISSUE THREAD

**Issue by garand** [roots/bedrock#224]
Have you considered setting the `WP_HOME` and `WP_SITEURL`'s dynamically?

For instance, adding the following to the config file and removing the corresponding entries from the `.env` file.

```
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/wp');
```

This would allow for an install that isn't dependent on a consistent hostname and making local development a bit easier. In my case, I run my local sites with the [built-in PHP web server](http://php.net/manual/en/features.commandline.webserver.php) with a random port number each time to prevent conflicts from multiple instances running.

**Comment by QWp6t** [comment]
Nah, we won't be adding this to bedrock, but you can do this in your `.env` file no prob.

Add this to your `.env` file...
```
WP_HOME="http://${HTTP_HOST}"
WP_SITEURL="${WP_HOME}/wp"
```

**Comment by garand** [comment]
Oh nice. Didn't know I could do it that way.

Curious on why you're against it though? Anything I'm missing that it breaks?

**Comment by QWp6t** [comment]
In production, it can result in duplicate content "penalties" since WP_HOME constant is used to determine canonical URLs, e.g., both www and non-www URLs to a post will be "canonical," and if you have any aliases for your domain, then they're canonical as well.

Plus I suspect it would take a giant shit all over multisite setups with subdomains. lol

**Comment by kalenjohnson** [comment]
What about HTTPS? Also, while it might be ok for development, it's probably not a great idea for production. You wouldn't want to assume that PHP's global vars are always 100% correct, I wouldn't want to rely on it for something so integral when it's an easy fix to set it as an env var.

And unfortunately, your case is a little edge case, it's the first time I've heard of someone using PHP's built in server for any extended period of time. Most people use Vagrant or some other local server set up

**Comment by garand** [comment]
Gotcha, thanks for the added insight! 👍
