### ISSUE TITLE
disallow_indexing & the blog_public override

### ISSUE THREAD

**Issue by ocasta** [roots/bedrock#228]
It would be useful to be able to disable the disallow_indexing feature in staging environments. This could easily be achieved by adding an additional environment variable. The current behaviour prevents plugins such as https://wordpress.org/plugins/restricted-site-access from functioning

**Comment by swalkinshaw** [comment]
We could potentially add a filter for it. But why not just delete the file? You could also add another action to override ours with higher priority.

**Comment by ocasta** [comment]
The problem with deleting the file is we would need to remember to do it whenever we re-install bedrock. 

I've worked round the issue adding the following to one of our plugins

         if ( WP_ENV === 'staging' && has_filter( 'pre_option_blog_public', '__return_zero' ) ) {
             remove_filter( 'pre_option_blog_public', '__return_zero' );
        }

**Comment by QWp6t** [comment]
well, the idea is that you keep that file in there throughout development, and then during staging. then remove when you push to production. could even make removal part of your deployment routine.

**Comment by swalkinshaw** [comment]
Closing this since it's non-standard and the solution that @ocasta posted is fine.
