### ISSUE TITLE
Use DB_CHARSET utf8mb4 by default

### ISSUE THREAD

**Issue by ideadapt** [roots/bedrock#230]
Since April 2015, WordPress uses utf8mb4 by default. It would be nice if you do so as well in config/application.php. 
When I got this error using `wp import export.sql`:

`ERROR 1366 (HY000) at line 215: Incorrect string value: '\xF0\x9F\x8C\xAE" ...' for column 'option_value' at row 1`

It cost me some time to realize, that my wp-config was wrong. 

Changing 
`define('DB_CHARSET', 'utf8');`
to
 `define('DB_CHARSET', 'utf8mb4');`
resolved it.

**Comment by swalkinshaw** [comment]
@ideadapt thanks, updated.
