### ISSUE TITLE
missing .env 

### ISSUE THREAD

**Issue by virtualLast** [roots/bedrock#231]
Hi just cloned the bedrock repo, ran composer install but the .env.example file wasnt generated - not sure if it is supposed to be or not, if not the install documentation needs updating to let people know they have to create that file

**Comment by QWp6t** [comment]
`.env.example` is already in the repo right here: https://github.com/roots/bedrock/blob/master/.env.example

According to the docs, you need to rename/copy that file to `.env` and then edit it.

https://github.com/roots/bedrock#installation
https://roots.io/bedrock/docs/installing-bedrock/
