### ISSUE TITLE
Content in 'app'?

### ISSUE THREAD

**Issue by bitwombat** [roots/bedrock#232]
I hope this doesn't come off as a troll, but does it make sense to have content in the 'app' dir?  I've always hated how wp-content has code (plugins) AND content (uploads) mixed together in wp-content... renaming it to 'app' doesn't fix this... just now we have content in the 'app' directory, instead of code in the 'content' directory!

On my own here?

**Comment by 16nsk** [comment]
I agree also, uploads have nothing to do with application and should be out of the "app" folder.

"/web/media" or "/web/assets" I find it making more sense, but "/web/uploads" would work too.

:+1:

**Comment by etcook** [comment]
@bitwombat That's not the issue and not why it wasn't 12 Factor Compliant. Having plugins and uploads under a single directly makes no difference. The key was removing wp-content (apps) from within WordPress (a library dependency unto itself.)

**Comment by swalkinshaw** [comment]
I don't really disagree with this. I guess it is "nicer" to have uploads outside of `app/` but at the time I don't know if it's worth it. This will sound funny since Bedrock does a ton of things to customize WP, but in general it's still better to keep the defaults when you can.

Roots/Sage used to have a custom uploads path to `/media` and it caused issues.

**Comment by kalenjohnson** [comment]
The other issue with Roots was it used redirects, which is where the source of the issues really lay.

However, it's not difficult to change this, the uploads folder can be changed with one constant defined: `define( 'UPLOADS', 'web/uploads/' );`

**Comment by bitwombat** [comment]
Reference:  https://codex.wordpress.org/Editing_wp-config.php#Moving_uploads_folder
and https://codex.wordpress.org/Function_Reference/wp_upload_dir

**Comment by QWp6t** [comment]
Closing this as it's simply an aesthetic change, i.e., a matter of taste. with no _functional_ benefit.

**Comment by bitwombat** [comment]
@QWp6t the first feature listed for Bedrock is "Better folder structure", which is what this is about.  If I understand best practices correctly, separating content from code is not merely aesthetic.

**Comment by FreshFlesh** [comment]
I agree with this.

If _functional benefit_ was the only concern for Bedrock, why renaming `wp-content` into `app` in the first place?
I don't see how having an `uploads` folder into an `app` folder is semantically correct.

Is there any other reason that would explain the choice not to move to the  `uploads` folder to its parent folder?

**Comment by bitwombat** [comment]
@etcook and @QWp6t do any of those points change your mind?

**Comment by retlehs** [comment]
> I don't see how having an uploads folder into an app folder is semantically correct.

it's not really semantically correct in `wp-content` either. just use the `UPLOADS` constant

> Is there any other reason that would explain the choice not to move to the uploads folder to its parent folder?

you can already do that pretty easily if you want. as @kalenjohnson mentioned:

```define('UPLOADS', 'web/uploads/');```

i completely agree that it should be `web/uploads/` (the old roots theme used to use `/assets/` in the webroot), but, we likely won't do this in bedrock as it's considered non-standard and usually frowned upon. by renaming `wp-content` to `app` we're not doing any harm, but the `uploads` directory naturally lives in the content directory on a wordpress installation. i guarantee there's plugins 'doing it wrong' and referencing the uploads directory relative to the content directory.

**Comment by etcook** [comment]
> @etcook and @QWp6t do any of those points change your mind?

There are too many plugins in use that rely on the relative location of uploads because that's been the "WordPress way" from the beginning. Working with the WP ecosystem is more often than not about striking a pragmatic balance between "best practices" and the realities of the ecosystem.
