### ISSUE TITLE
Converting old WP structure to Bedrock

### ISSUE THREAD

**Issue by ionut-tanasa** [roots/bedrock#235]
Hi guys,

I tried googling a bit on how to convert an "old" WordPress folder structure to Bedrock. I didn't found much or maybe I didn't google well enough :)

Do you have any tips and tricks ? Or some kind of guide to migrate any wp instance to bedrock.

I tried moving the various bits and pieces following the folders structure. But I ended up with a huge amount of errors. I think moving the files and folders around doesn't do it.

Any help would be appreciated :) 

Thank you.

**Comment by ollietreend** [comment]
Hey @ionut-tanasa 

The best way to migrate your site would be to start with a fresh install of Bedrock WordPress, and just migrate across the themes and plugins from your old installation. In theory, the only files that you've changed in your old install will all exist inside the `wp-content` directory.

In bedrock, the directory `web/app` serves the same purpose as `wp-content` – it just has a different name. Therefore you should be able to simply move all subdirectories of `wp-content` over to bedrock's `web/app` directory.

**Comment by retlehs** [comment]
as stated in our contributing guidelines (that are linked at the top when you go to create a new issue), please don't use github issues for personal support requests.

https://discourse.roots.io/
