### ISSUE TITLE
Switch from Dotenv/env file to an INI file

### ISSUE THREAD

**Issue by swalkinshaw** [roots/bedrock#240]
See https://github.com/roots/bedrock/pull/239 for more background.

> The .env file has one main purpose: it keeps your "secrets" in a separate file out of version control. But this comes with downsides: 1) exposes things to phpinfo, and more importantly, 2) exposes the env vars to any child processes.
> 
> In our case, there's no actual reason to use real environment variables. We just need a simpler way of setting variables for use in config files.
> 
> We're pretty sure we're going to switch to an ini file in the future since PHP has parse_init built-in. Because of this, I'm going to close this PR.

We may wait until 5.5 is EOL since PHP 5.6.1 has a very useful [feature](http://php.net/manual/en/function.parse-ini-file.php) with simple type coercion built-in like we had with Dotenv.

**Comment by jamesgol** [comment]
Why not just add something like the PR (but make it so default is to unset vs how I did it) for the interim and keep the dotenv support for backwards compatibility, then add in the parse-ini as an option that people can migrate to assuming they have > 5.6.1.  The code to do both isn't very complicated.

For the ini file you could have a subcategory that everything in it just gets used as a key pair for a define and then other subcategories could be used for other future uses.

**Comment by donaldallen** [comment]
To be clear, are you referring to the ```parse_ini_file()``` function?

**Comment by donaldallen** [comment]
Doesn't the PHP dotenv readme indicate that you shouldn't use it in production?

**Comment by swalkinshaw** [comment]
@donaldallen kind of. See here: https://github.com/bkeepers/dotenv#multiple-rails-environments

**Comment by bjorn-ali-goransson** [comment]
How about JSON? Could be easier, if more complex structures were needed (they are automatically converted to arrays and expando `stdClass` objects when using `json_decode`...)

**Comment by jamesgol** [comment]
A huge disadvantage to JSON is the lack of comments

**Comment by bjorn-ali-goransson** [comment]
YAML?

2016-03-24 22:57 GMT+01:00 James Golovich <notifications@github.com>:

**Comment by mAAdhaTTah** [comment]
You need comments in your environment variables?

**Comment by bjorn-ali-goransson** [comment]
There's an instructional comment in `.env.example` that says how to generate salts from wordpress.org.

Also, commenting out stuff (rather than *commenting stuff*) is handy from time to time

**Comment by dlundgren** [comment]
You might want to look at `josegonzalez/dotenv`. I switched to it from `vlucas/phpdotenv` because I didn't like the variables being leaked into the environment. By default `josegonzalez/dotenv` will only export into the environment when told to.

I use the following in my non-wordpress projects:
```php
$envLoader = new \josegonzalez\Dotenv\Loader(ROOT_PATH . '/.env');
$envLoader->parse();

$env = $envLoader->toArray();
```

I then access the array for what I need. There is an `expect()` function that does the same as `required()`.

**Comment by QWp6t** [comment]
> Characters `?{}|&~!()^"` must not be used anywhere in the key and **have a special meaning in the value**. 

http://php.net/manual/en/function.parse-ini-file.php

Does anyone know what the "special meaning" is that they're talking about? It seems like this might not play well with generated salts.

**Comment by COLABORATI** [comment]
Please just include a plain php file, then it is also possible to remove that unneeded autoloader overhead. This is wordpress, it is not java or rails or django, keep it simple. If the goal is to keep config values out of the repo, then this is the most direct way to achieve it. Just plain php in the config folder. Look at this thread and learn what complications that dotenv overhead created - do not overcomplicate things. Keep it simple. Thanks!

**Comment by COLABORATI** [comment]
Re the ini file special character issue: 
http://stackoverflow.com/questions/36458964/wrong-output-of-ini-file-after-parsing/36459482#36459482

**Comment by sandrodz** [comment]
I like `.env` files, I'm used to them in Laravel, ROR. please don't remove it.

**Comment by swalkinshaw** [comment]
Closing this since there isn't a pressing need for it anyway. Bedrock is stable as is.
