### ISSUE TITLE
Instructions for IIS Express

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [roots/bedrock#246]
Hi,

Bedrock actually works on IIS Express, the only thing lacking is proper rewriting to the `web/` directory, and the fact that Wordpress (something lacking inside `wp_guess_url` I think) redirects the installer to `http://localhost:12345//wp/wp-admin/install.php` with a  double slash (`//`).

Adding a `web.config` in the site root with the following contents solves these issues:

    <configuration>
      <system.webServer>
        <rewrite>
          <rules>

            <clear/>

            <rule name="Remove multiple slashes" patternSyntax="ECMAScript" stopProcessing="true">
              <match url=".*" />
              <conditions>
                  <add input="{UNENCODED_URL}" pattern="([^/]*)/{2,}([^/]*)" />
              </conditions>
              <action type="Redirect" url="{REQUEST_URI}" />
            </rule>

            <rule name="Bedrock web" stopProcessing="true">
              <match url="(.*)" />
              <conditions logicalGrouping="MatchAll">
                <add input="{PATH_INFO}" negate="true" pattern="/web/.*" />
              </conditions>
              <action type="Rewrite" url="/web/{R:1}" />
            </rule>
        
          </rules>
        </rewrite>
      </system.webServer>
    </configuration>

Coming up with this config was kind of cumbersome, and I can imagine a lot of developers having troubles with it (if they even dare to try). So it's valuable information.

Can we provide this (and similar) *centralized* (i.e. put it somewhere) guidance to those who wish to run Bedrock on this stack?

**Comment by swalkinshaw** [comment]
Right now the documentation around webserver configuration for Bedrock is pretty sparse. We briefly mention it here https://roots.io/bedrock/docs/installing-bedrock/.

We could add a separate page with snippets for Nginx, Apache, and IIS as well.

Would you be interested in doing a PR for this on our [docs](https://github.com/roots/docs) repo? We could help fill out the  Nginx or Apache sections if you aren't as familiar with them.

**Comment by bjorn-ali-goransson** [comment]
Sounds like a plan. I'll make a PR there when it's done.

**Comment by TWG-Matt** [comment]
@bjorn-ali-goransson I'm not that familiar with IIS and I'm trying to get this setup using your instructions but I'm having now luck.

When I view the site using localhost/ I get the following error.

403.18 - Forbidden 'The specified request cannot be processed in the application pool that is configured for this resource on the Web server.'

This is odd as I have 5 other WordPress sites configured and running on this server.  They are not using bedrock though.

In the Detailed Error Information I have these two items but they are wrong.
Requested URL: http://localhost:80/web/
Physical Path: D:\Web\Sites\web\

When they should be:
Requested URL: http://localhost:80/site1/web/
Physical Path: D:\Web\Sites\site1\web\
