### ISSUE TITLE
URL issues on multisite

### ISSUE THREAD

**Issue by felixarntz** [roots/bedrock#250]
I have recently set up my first multisite with Bedrock, and I have encountered several issues where the URLs are not correct. After some investigation, I figured that the issues are a result of a problem in WordPress Core - in some places it does not honor the site URL setting. This is no problem with a regular WP install, but when WordPress is installed in a subdirectory as it is in Bedrock, the site URL is different from the home URL.

The most significant problem is that some areas in the network admin will direct me to /wp-admin instead of /wp/wp-admin, for example when you're on the My Sites section and click on "Edit Site".

To be clear, this is not a Bedrock bug, but I think it would be great if Bedrock provided a fix for it, so that other people do not run into this problem. While there are ways to workaround this with nginx / htaccess rewrites, I'd prefer to actually fix it from the code site. As of now, I have fixed these issues on my site, so I'll create a pull-request with my approach.

Btw I also created a ticket on Core Trac, the first responses told me that WP doesn't officially support this - so not sure whether there will be a Core fix soon.

**Comment by iandunn** [comment]
x-ref: https://core.trac.wordpress.org/ticket/36507

**Comment by sandrodz** [comment]
I've created multisite using bedrock, I've messed around with configs and options saved in DB and everything seems to work fine, all urls redirect correctly.

**Comment by sandrodz** [comment]
This is example .htaccess I shipped with project.

<img width="577" alt="screen shot 2016-11-26 at 3 55 17 pm" src="https://cloud.githubusercontent.com/assets/8479569/20640174/c58cce52-b3f0-11e6-8cab-1069d2319e4a.png">

<img width="516" alt="screen shot 2016-11-26 at 3 57 10 pm" src="https://cloud.githubusercontent.com/assets/8479569/20640202/172fa2c0-b3f1-11e6-8293-d79325022c61.png">

**Comment by sandrodz** [comment]
Btw, I'm including this info for someone who might end up here before your fixes are merged! I'm not suggesting this as a better solution or smth, your PR is awesome.

**Comment by dubcanada** [comment]
Adding

    $url .= 'wp/';

To network_site_url function in link-template.php fixes it, but that's obviously not a correct fix.

For now what I did was use the network_site_url filter to fix the urls.

**Comment by henscu** [comment]
@sandrodz do you have your example .htaccess and nginx configs above in a gist or webpage so that they can be easily cut and pasted?

**Comment by sandrodz** [comment]
@henscu no, but I can provide them. I didn't think it would be useful :) I have a very nice docker dev env for wp and laravel with respective nginx configs - I'm planning to share it soon - it contains correct configs for multisite too.

**Comment by henscu** [comment]
@sandrodz that would be great. I'm also working on getting my Docker env going, and am looking at the entire workflow from initial generation of WP database & code in Vagrant using Trellis, then migrating the db from inside Vagrant to use with Docker and merging upstream changes from Trellis etc... I'm not sure if anyone else has done this yet...

**Comment by swalkinshaw** [comment]
From https://github.com/roots/bedrock/pull/251:

> I think this should be a separate plugin/package. Although the problem happens with Bedrock, it's a WP but not a Bedrock one.

> If this was a standalone package, Bedrock could require or at least recommend it.

**Comment by smarterdigitalltd** [comment]
Hi all, I'm just going to leave this link here: https://github.com/felixarntz/multisite-fixes/blob/master/mu-plugins/wpms-site-url-fixer.php

It's not mine, but it works well for me. I've tried many times to get multisite (subdomain) + bedrock working on a managed WP host (I'm with Kinsta) with no luck, but after another 6 hours of tearing my hair out today, I stumbled across this.

Simply add it as an mu-plugin and define a constant in application.php for

`define('WP_CORE_DIRECTORY', 'wp');`

and that's it.

**Comment by felixarntz** [comment]
@smarterdigitalltd I specifically wrote this with Bedrock in mind :)

**Comment by JulienMelissas** [comment]
Hey everyone! I've finally had a chance to take a look at this ticket. Please check out https://github.com/roots/multisite-url-fixer and see if it works for you 😄  - it's working on my multisite for sure right now. If in fact it's working for everyone, I'll add it to packagist and to the bedrock multisite docs. Would love feedback ASAP.

Thanks again to @felixarntz for the og code (hi Felix!!).

**Comment by felixarntz** [comment]
Very happy to read that this is now in official hands - thanks @JulienMelissas! :)

**Comment by Preen** [comment]
Im getting
>Not Found The requested URL /wp-signup.php was not found on this server.

with

```
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true);
define('DOMAIN_CURRENT_SITE', env('DOMAIN'));
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1); 
```

Whenever I activate that plugin and use that config. Is there a guided tutorial somewhere to get multisite up n running with bedrock?

**Comment by greatislander** [comment]
@JulienMelissas The new plugin seems to be working for me. One question though… in @felixarntz's original repo, it says:

> Everything here should only be used for subdomain (or domain) setups. Do not use with subdirectory setups!

Does this still apply? Thanks in advance.

**Comment by JulienMelissas** [comment]
@greatislander, we're working on that over here: https://github.com/roots/multisite-url-fixer/pull/2/

Would you be willing to test? Would be a great help for me and maybe I could then close out these issues and finish this all up! Thanks.

**Comment by greatislander** [comment]
@JulienMelissas will do 👍

**Comment by JulienMelissas** [comment]
Thanks for the feedback and testing @greatislander! I'm going to close this now with the solution of people using https://github.com/roots/multisite-url-fixer. [Bedrock Docs are coming](https://github.com/roots/docs/pull/117).

**Comment by JulienMelissas** [comment]
@Preen - regarding your issue, can you please make a thread on Discourse and maybe someone can help you there? I think your issue might lie in `define('DOMAIN_CURRENT_SITE', env('DOMAIN'));`.
