### ISSUE TITLE
plugindir constant does not point to the right folder

### ISSUE THREAD

**Issue by timotheemoulin** [roots/bedrock#255]
Hi all,
I'm using bedrock on a few Wordpress sites now and I'm confronted for the first time to the following issue.

The `PLUGINDIR` constant defined in *wp-includes/default-constants.php:160* does not point to the right folder. The relative path to the plugin directory should point to "app/plugins" instead.

I added `define('PLUGINDIR', '../app/plugins/');` in my *index.php* file before requiring Wordpress and everything seems to work correctly.

Here is my new *index.php*
``` php
<?php

/** WordPress view bootstrapper */
define('WP_USE_THEMES', true);
define('PLUGINDIR', '../app/plugins/');
require(__DIR__ . '/wp/wp-blog-header.php');

```

Can anyone confirms?
tim

**Comment by QWp6t** [comment]
That constant is deprecated. It is [not used anywhere internally](https://github.com/WordPress/WordPress/search?q=PLUGINDIR). If a theme or plugin author is using it, they're [doing it wrong](https://codex.wordpress.org/Determining_Plugin_and_Content_Directories).

But yeah, feel free to define it if you need it.

**Comment by timotheemoulin** [comment]
Well it is still in use in some old plugins.
Thanks
