### ISSUE TITLE
Disable asset caching on development & staging environments, but allow it in production

### ISSUE THREAD

**Issue by k1sul1** [roots/bedrock#263]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

---

**What is the current behavior?**

I was having some troubles with browser caching assets on my local Trellis installation, and sometimes I was facing a bug type of "this shouldn't happen", mostly because of the browser cache. 

**What is the expected or desired behavior?**

Setting a version to be the unix epoch like this fixed the problem.

`wp_enqueue_script("theme-js", get_template_directory_uri() . "/dist/js/bundle.js", array(), date("U"), true);`

But because I want to leverage browser caching on production environments, I did this to get rid of the version.

`  
if (WP_ENV === 'production' && !is_admin()) {
    add_theme_support('soil-disable-asset-versioning');
}
`

So I'm suggesting adding this as a additional mu-plugin to bedrock.

## Feature Request

**Please provide use cases for changing the current behavior:**

Disables browser caching on development & staging servers, enough said?

**Comment by swalkinshaw** [comment]
Not sure exactly what was going on in your case and what the problem was, but even if you wanted some functionality like this in an mu-plugin it's not something that should be included in Bedrock by default.

Bedrock shouldn't have specific code to integrate with other Roots projects. And this is Soil specific. Not default WP behaviour.

**Comment by k1sul1** [comment]
I think it's pretty much the same thing as the disallow indexing mu-plugin, but that's just my opinion. Soil was just an example, and as you must know, this is very trivial thing to do, but often overlooked (or forgotten). 

https://github.com/roots/soil/blob/master/modules/disable-asset-versioning.php
