### ISSUE TITLE
Please add info about how to update wordpress after deployment

### ISSUE THREAD

**Issue by COLABORATI** [roots/bedrock#272]
If I am not missing anything there is no information anywhere in the documentation about how to **update** a live wordpress installation with bedrock. This is quite delicate as the default bedrock configuration sets ```define('AUTOMATIC_UPDATER_DISABLED', true);```.

I understand that you would like to provide a good and modern wordpress stack, however the most important part in wordpress management is updating - by disabling automatic updates you are basically advising people to deploy timebombs.

There should be at least some very prominently placed information in the documentation that describes all the needed steps to manually update wordpress, (plus some information on how to automate this or where to get alerts about needed action). Example:

## How to update with bedrock
We disable the automatic updater, so you have to take care for updating your site manually to keep your site secure. This can be done like this:
* check for wordpress updates every hour somewhere on the internet.
* when there are updates for wordpress core, check if the update is available via composer
* when there are updates to one of your installed plugins or themes, check if the update is available via composer
* if you allowed website administrators to install plugins via the wordpress admin gui (not recommended), please first synchronize your composer config with your installed plugins
* edit the composer configuration file to reflect the new versions of all updated plugins
* update your site with composer
* sync your update to your local development site

This is just a short overview of the update process, it should be of course described in detail with all the needed file edits and commands so everybody is able to follow.

**Comment by retlehs** [comment]
turns out we don't even need `AUTOMATIC_UPDATER_DISABLED` because we already set `DISALLOW_FILE_MODS` in production

wordpress also checks to see if your installation contains a `.git` directory and will disable updates if it finds one

we're always open to better docs. we've got a repo that you can contribute to at https://github.com/roots/docs

**Comment by COLABORATI** [comment]
Yes, I contributed here, please just copy paste what you want, thanks for your attention and good luck!
