### ISSUE TITLE
possible conflict with qtranslate-x plugin

### ISSUE THREAD

**Issue by sandrodz** [roots/bedrock#279]
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

---

**What is the current behavior?**

when I visit wp-admin it is being redirected to wp/ with 404 error

**What is the expected or desired behavior?**

when I visit wp-admin redirect to wp/wp-admin

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Install bedrock, go to permalinks save, wp-admin redirect works.
Now install qtranslate-x 
hit wp-admin it is being redirected to wp/ with error 404

**Please describe your local environment:**

Bedrock version: latest

WordPress version: 4.6.1

PHP version: 7

OS: alpine

qtranslate-x: 3.4.6.8

**Comment by swalkinshaw** [comment]
Sounds like that plugin is at fault. If you check your error messages maybe you can report the bug to them. Bedrock uses standard WP methods for customization, so if a plugin is not compatible, then they are doing something wrong.

**Comment by sandrodz** [comment]
@swalkinshaw thanks! my plan was to report to both of you guys anyways :)
