### ISSUE TITLE
multisite bedrock auto updated WordPress

### ISSUE THREAD

**Issue by sandrodz** [roots/bedrock#280]
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)
---

**What is the current behavior?**

multisite WordPress auto updated, files were pushed to root directory instead of WP. Only parent got updated, child sites were not updated.

**What is the expected or desired behavior?**

WordPress auto updated is disabled, only possible via composer.

---

## Bug report

Unfortunately I don't know how this happened, I can provide site files + db for investigation if required.

**Where did the bug happen? Development or remote servers?**

Happened in production.

**Comment by retlehs** [comment]
not sure how this is even possible since bedrock uses `define('AUTOMATIC_UPDATER_DISABLED', true);`

https://github.com/roots/bedrock/blob/2162a7defd19f7a2229e5ede5223d729b95d6efb/config/application.php#L74

**Comment by sandrodz** [comment]
@retlehs I know. Also this: https://github.com/roots/bedrock/blob/2162a7defd19f7a2229e5ede5223d729b95d6efb/config/environments/production.php#L7

I think there is something funky with multisite installation, maybe its worth investigating?

**Comment by sandrodz** [comment]
So https://github.com/roots/bedrock/blob/2162a7defd19f7a2229e5ede5223d729b95d6efb/config/environments/production.php#L7 this disabled manual WP update by admin via GUI. Is it possible that this doesn't work for multisite? or has different effect?

**Comment by swalkinshaw** [comment]
Closing since without any more occurrences or details. Feel free to re-open this if you've done more investigation.
