### ISSUE TITLE
wp-cli

### ISSUE THREAD

**Issue by strarsis** [roots/bedrock#284]
I can't find wp-cli in vendor/bin after creating the project with composre (based of bedrock).
Do I have to install wp-cli as separate tool globally on system?

Related: https://github.com/roots/bedrock/issues/14

**Comment by swalkinshaw** [comment]
Yes. See their installation docs: http://wp-cli.org/#installing

**Comment by strarsis** [comment]
Thanks! I thought it is installed automatically or as project-local dependency.
It would be nice if this is hinted more in README.

**Comment by swalkinshaw** [comment]
WP-CLI recommends using the global phar installation method which is why we removed it. Bedrock isn't dependent on it at all, we just include a config file to make integration easier.
