### ISSUE TITLE
URL issue with Advanced WP Columns plugin

### ISSUE THREAD

**Issue by strarsis** [roots/bedrock#285]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Advanced WP Columns iframe-popup in text edtior opens `/wp-content/plugins/advanced-wp-columns` 
which result in HTTP 404:
````
NOT FOUND

Sorry, but the page you were trying to view does not exist.
````

**What is the expected or desired behavior?**

Advanced WP Columns irame-popup should load correctly the columns editor interface.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. Install Advanced WP Columns plugin.
2. Activate Advanced WP Columns plugin.
3. Open a page in editor.
4. Select Advanced WP Columns button.

**Please describe your local environment:**

Bedrock version: Bedrock 1.7.3

WordPress version: WordPress 4.7

PHP version: PHP 7.1

OS: Debian Jessie amd64

**Where did the bug happen? Development or remote servers?**

Development (docker/docker-compose).

---

**Other relevant information:**

In Bedrock, plugins are installed to `app/plugins` (where also the folder 'advanced-wp-columns' resides).

The Advanced WP Columns plugin seems to have the default WordPress path hardcoded instead as it opens the iframe popup pointing to it using this default path instead the new one used in Bedrock installations.

**Comment by austinpray** [comment]
>The Advanced WP Columns plugin seems to have the default WordPress path hardcoded instead as it opens the iframe popup pointing to it using this default path instead the new one used in Bedrock installations.

There's nothing we can do about this on our side. This is an issue with that plugin itself.

**Comment by strarsis** [comment]
@austinpray: But this would be fixable in plugin by looking up the plugins path 
instead having it hardcoded as it is now?

**Comment by swalkinshaw** [comment]
Yes it's fixable by the plugin, not by us. They are doing things the wrong way.
