### ISSUE TITLE
Default themes not showing up.

### ISSUE THREAD

**Issue by royalfox** [roots/bedrock#287]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Wordpress default themes not showing up in Admin Appearance menu. Not loading the themes from the wp directory. This happens when I did composer install and setup the site with the config settings.

**What is the expected or desired behavior?**

Before I was able to see and/or activate the themes that was in the wp directory without having to copy and paste the folders into the app directory.

---

## Bug report

**Where did the bug happen? Development or remote servers?**

Development local server.

**Comment by retlehs** [comment]
unable to reproduce. https://github.com/roots/bedrock/blob/master/web/app/mu-plugins/register-theme-directory.php ensures that core wp themes are available 

fresh bedrock install:

![image](https://cloud.githubusercontent.com/assets/115911/21756677/80ffd62c-d5e1-11e6-9d8a-0f57b7f4db50.png)

please post on https://discourse.roots.io/ if you need further support
