### ISSUE TITLE
github-updater as alternative or addition to composer?

### ISSUE THREAD

**Issue by strarsis** [roots/bedrock#293]
Some WordPress plugins hosted on Github propose to use the github updater plugin which can update plugins from Github and other hosted repos directly (https://github.com/afragen/github-updater).

This may be a server-side alternative to composer, 
it also allows locking dependencies but still upgrading in production for critical patches.

**Comment by thisolivier** [comment]
You can add any number of external repos through composer, what functionality do you feel it doesn't provide?

**Comment by strarsis** [comment]
composer can also install from sources like Github but this plugin can update in production automatically.
