### ISSUE TITLE
DotEnv Exception

### ISSUE THREAD

**Issue by moazam1** [roots/bedrock#294]
I am randomly getting following annoying error:

`Uncaught exception 'Dotenv\Exception\ValidationException' with message 'One or more environment variables failed assertions: DB_NAME is missing, DB_USER is missing....`

I have switched from env function \Env::get but didn't solve my problem. Has anyone encountered this issue before? We have couple different environments setup on different servers instances i.e. PHP 5.6, PHP 5.5 and PHP 7 and we are getting same error on all servers. Any help will be greatly appreciated. Thanks

**Comment by QWp6t** [comment]
php might not have permission to read your .env file, or it doesn't exist, or it's empty. That's my guess. But this should probably be taken upstream to the DotEnv repo.

**Comment by moazam1** [comment]
Thanks. It works fine most of the time just randomly throwing error. I asked here because bedrock is using dotenv so wanted to ask alternative or workaround.

**Comment by swalkinshaw** [comment]
This can't really be a Bedrock issue itself. Either an environment thing or an upstream issue with Dotenv (although I doubt that).
