### ISSUE TITLE
Make the "web" directory configurable through DotEnv

### ISSUE THREAD

**Issue by themccallister** [roots/bedrock#296]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

**Please describe your local environment:**

Bedrock version: latest

WordPress version: 4.7.2

PHP version: 7.0.15

OS: macOS/Docker/Ubuntu

## Feature Request

The `$webroot_dir` variable is currently hard coded to web. However, some environments require this to be `html`, `public` or etc. 

**Please provide use cases for changing the current behavior:**

If the `$webroot_dir` variable was defined through the DotEnv, and defaulted to the string `web` if not defined, this would make it easier to customize the installation per environment.

**Comment by swalkinshaw** [comment]
It's not that easy unfortunately.

There are references to `web/` in `composer.json` which can't be done dynamically. `wp-cli.yml` has a reference as well but that's less important.

**Comment by swalkinshaw** [comment]
I'm going to close this since it would require manual modifications anyway which people are free to do currently. `.gitignore` is another place for example.

Maybe a doc page on switching the webroot would be useful. PRs can be done at https://github.com/roots/docs

**Comment by Snaver** [comment]
You can use symlinks to get round this issue, so if you require html/ to be your document root simply run the command: `ln -s web/ html`

I had to do this when setting up Docker support, working example can be seen here https://github.com/Snaver/bedrock.
