### ISSUE TITLE
[Feature Request] Move Autoloader to its own repository

### ISSUE THREAD

**Issue by vinkla** [roots/bedrock#299]
It would be nice if we could use the autoloader outside of Bedrock. Would it be possible to move the class to its own Composer package or its own plugin?

**Comment by swalkinshaw** [comment]
Agreed but unfortunately I don't think it's possible :(

The autoloader is needed so that mu-plugins via Composer work, so it can't be a package itself. And it could be a normal plugin, but we only use Composer to manage plugins in Bedrock.

**Comment by vinkla** [comment]
Oh, okay. Too bad :(

**Comment by aaemnnosttv** [comment]
I've been wondering the same for a while now and think this is worth revisiting.

@swalkinshaw it can't be entirely implemented as a package without using a custom loader, etc, but it should be entirely possible to install `Autoloader` as a regular package that lives in the vendor directory. Then the mu-plugin in Bedrock could be drastically simplified like so:

```php
/** file header... */

namespace Roots\Bedrock;

if (is_blog_installed() && class_exists(Autoloader::class)) {
    new Autoloader();
}
```

So, I think even though there would still be some very minimal "wiring" necessary to make it work, it would still be valuable as a package. It's also a substantial chunk of the project which isn't really intended to be boilerplate.

**Comment by Log1x** [comment]
I think this is a good idea and I'd be willing to rewrite the autoloader (or at the very least, clean it up).

**Comment by QWp6t** [comment]
we could write a composer plugin that copies the autoloader to mu-plugins folder

**Comment by aaemnnosttv** [comment]
@QWp6t that sounds a bit unnecessary considering the simplicity of the integration. Then you would be looking at 3 packages instead of one:

* Autoloader package
* Bedrock Autoloader installer Composer plugin
* Bedrock Autoloader package that uses both

I think a Composer plugin would be more justified if the mu-plugin required some dynamic component that the plugin would generate.

**Comment by austinpray** [comment]
Started work on this: https://github.com/roots/bedrock-autoloader

I made all the proper sacrifices to the git gods such that the autoloader's commit history made it to the new repo :+1:

**Comment by swalkinshaw** [comment]
I agree this is a worthwhile improvement 👍

**Comment by austinpray** [comment]
[Making issues here](https://github.com/roots/bedrock-autoloader/issues) as they come to mind. Feel free to grab some of them off the stack! @aaemnnosttv @vinkla and other friends: feel free to add more issues to the pile if I am missing anything

**Comment by vinkla** [comment]
I think this a step in the right direction. We actually published [`wordplate/autoloader`](https://github.com/wordplate/autoloader) a while back and then later decided to merge the mu-loader into the [`wordplate/framework`](https://github.com/wordplate/framework/blob/f390028188e703fa2e65b9a2873f0667cd9fe5c5/src/PluginLoader.php) package instead.

The developers behind WordPlate have always been impressed by the work of Roots. We install the `roots/wp-password-bcrypt` package for every new WordPlate application. It would be really cool if we could work on an autoloader together and share the logic between the projects. I'll head over to the new repository and send over a pull request or two.

**Comment by retlehs** [comment]
#519
