### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by lautreamont3** [roots/bedrock#30]
There is a problem with language support (again). In this setup seting ```WPLANG``` to something does not do the trick because WP does not expect ```language``` directory in ```wp/wp-content``` but in ```app```. If I wanted to work, I must move directory manually after ```composer install``` and before wordpress installation. Is there a way to tell composer to do this. For some reason themes works from ```wp/wp-content``` but ```language``` not.

**Comment by royduin** [comment]
Any updates on this? Currently languages are installed in the `web/app/languages` directory, Bedrock doesn't ignore this so by default languages needs to be commited in the projects repository. Maybe integrate this: https://discourse.roots.io/t/install-update-wordpress-languages-with-composer/2021 ?

**Comment by swalkinshaw** [comment]
@royduin we're still just letting people deal with this as they want to since there's a couple solutions. You can just add those gitignore rules yourself though.

**Comment by louim** [comment]
I believe a page in the wiki explaining solutions would be helpful for those who haven't seen the forum. Anyone volunteer to create it?
