### ISSUE TITLE
Redirected you too many times after change wp directory

### ISSUE THREAD

**Issue by ihsanberahim** [roots/bedrock#300]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [X] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

---

**What is the current behavior?**

This is fresh installation attempt. 
Face redirection issue in the installation page.

`local.dev/backend/wp-admin/install.php`

**What is the expected or desired behavior?**

it should be fine after i changed the directory setting in these files:

```
site/wp-cli.yml
site/composer.json
site/config/application.php
site/web/index.php
```

---

## Bug report
**Please provide steps to reproduce, including full log output:**

i changed `web/wp` to `web/backend` then it happen.

**Please describe your local environment:**

Bedrock version:  1.7.5

WordPress version: - (not yet able to install because of this redirection issue)

PHP version: 7.1

OS: MacOSX

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/c/bedrock) thread or were any utilized (please link them)?**

[Changing WordPress’s core `wp` directory](https://discourse.roots.io/t/changing-wordpresss-core-wp-directory/8209/7?u=ihsanberahim)

**Comment by QWp6t** [comment]
This works. I've done it many times. And it certainly isn't a bug in Bedrock.

**Comment by ihsanberahim** [comment]
is it you change the `wp` directory name in these files?
```
site/wp-cli.yml
site/composer.json
site/config/application.php
site/web/index.php
```
