### ISSUE TITLE
Add languages folder to gitignore

### ISSUE THREAD

**Issue by strarsis** [roots/bedrock#303]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

---

**What is the current behavior?**

languages folder is not ignored by git, updated language files (from plugins) are committed while 
the plugins/core files themselves are not committed but installed using composer or 
WordPress installer/updater (notably on the dev environment).

**What is the expected or desired behavior?**

languages folder is ignored by git and language files are installed/updated with their plugins.

**Is there a related [Discourse](https://discourse.roots.io/c/bedrock) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/why-are-themes-in-repository-not-ignored-too/8924/8?u=strarsis

## Feature Request

Are there use cases where it makes sense not ignoring the languages folder?
Like translations for the main theme (that is usually managed with the same bedrock repository), 
custom translations or just in time changes?
In this case the developer could un-ignore the particular folders or files in languages folder and 
commit a modified .gitignore.

**Comment by swalkinshaw** [comment]
As discussed in that thread, the only things in the `.gitignore` by *default* are folders which are managed by Composer.

Since languages don't fit into that, they aren't ignored.

**Comment by strarsis** [comment]
If [managing WordPress language with composer packages worked with all packages](https://wp-languages.github.io/), would it then make sense to gitignore the language files, too?

**Comment by swalkinshaw** [comment]
Yeah and if that was our official recommendation. I just don't have enough experience with it and other members of Roots don't use languages much.
