### ISSUE TITLE
johnpblock/wordpress update

### ISSUE THREAD

**Issue by sw33tr** [roots/bedrock#305]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [ ] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Looks like johnpblock/wordpress package has updated it is now a meta-package that requires the core installer and johnpbloch/wordpress-core
See
https://twitter.com/johnpbloch/status/843118287760379906
deploys now fail for me - no wordpress is installed in wp folder. I might be doing something wrong though :)

```
TASK [deploy : WordPress Installed?] *******************************************
System info:
  Ansible 2.1.2.0; Darwin
  Trellis at "Ensure there is always at least one PHP-FPM pool defined"
---------------------------------------------------
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
fatal: [IP......]: FAILED! => {"changed": false, "cmd": ["wp", "core", "is-installed"], "delta": "0:00:00.157565", "end": "2017-03-25 21:16:44.069902", "failed": true, "failed_when_result": true, "rc": 1, "start": "2017-03-25 21:16:43.912337", "stderr": "Error: This does not seem to be a WordPress install.\nPass --path=`path/to/wordpress` or run `wp core download`.", "stdout": "", "stdout_lines": [], "warnings": []}

```
If I try to 1 remove old package from composer.json, 2. Run composer update, 3. Cleared composer cache, 4. require new package  a new wordpress folder is installed and wp is empty.

**What is the expected or desired behavior?**

install wordpress

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

1. remove old package from composer.json, 2. Run composer update, 3. Cleared composer cache, 4. require new package 

**Please describe your local environment:**

Bedrock version: 1.7.2
WordPress version: 4.7.3

PHP version: 7.0

OS: Ubuntu 16.04.1

**Where did the bug happen? Development or remote servers?**

both

**Is there a related [Discourse](https://discourse.roots.io/c/bedrock) thread or were any utilized (please link them)?**

X

**Comment by fullyint** [comment]
Most users find that these steps resolve the issue: https://discourse.roots.io/t/johnpbloch-wordpress-moved-to-a-new-configuration-and-wp-goes-missing/9124/45

I'm closing this because there is no code nor bug to be fixed in Bedrock.
