### ISSUE TITLE
Disable REST API by default?

### ISSUE THREAD

**Issue by royduin** [roots/bedrock#308]
Just like Bedrock is adding this https://github.com/roots/wp-password-bcrypt by default for better security, maybe it's good to disable the REST API (which is present and enabled by default since Wordpress 4.7)? For example by adding this plugin: https://wordpress.org/plugins/disable-json-api/

**Comment by swalkinshaw** [comment]
Not sure we can do this by default. Plugins could easily rely on it? bcrypt is seamless so that's different.

**Comment by royduin** [comment]
I can't name one who does.

**Comment by mAAdhaTTah** [comment]
`wp-admin` itself is going to increasingly rely on API, and the API itself is going to become an increasingly important part of the ecosystem, although it obviously isn't yet. I would be opposed to bedrock disabling such a major feature by default, as its strength is going to be in the sheer number of sites that support it..

**Comment by swalkinshaw** [comment]
Ditto
