### ISSUE TITLE
Two packages cannot share the same directory (johnpbloch/wordpress rename)

### ISSUE THREAD

**Issue by jakejohns** [roots/bedrock#309]
i think this may be relevant, as I had this issue with an existing roots install.
https://github.com/Seravo/wordpress/issues/55

**Comment by swalkinshaw** [comment]
This isn't directly an issue with Bedrock. But anyone who wants more information and solutions can read this: https://discourse.roots.io/t/johnpbloch-wordpress-moved-to-a-new-configuration-and-wp-goes-missing/9124/1

Generally the solution is:

```bash
composer remove johnpbloch/wordpress

composer clear-cache

composer require johnpbloch/wordpress:4.7.3
```

**Comment by justingivens** [comment]
you can also just remove vendor/johnpbloch folder before running `composer update` or `composer install`

**Comment by tucq88** [comment]
@justingivens How smart. I followed a guide in forum which suggest me to remove page in composer, run update, clear cache, then re-add with latest version. And your guide is just the same but so much quicker. Thanks mate.

**Comment by bmeiser** [comment]
@tucq88 @justingivens Agreed.  Saved me lots of time and stress for my 50+ Wordpress install updates :)
