### ISSUE TITLE
/web/app/themes folder isn't being used

### ISSUE THREAD

**Issue by gretzky** [roots/bedrock#314]
## Submit a feature request or bug report

- [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Following the installation instructions from Roots/Trellis docs, Bedrock isn't looking at /web/app/themes/ folder for themes, instead it's using wp-content/themes. 

**What is the expected or desired behavior?**

Supposed to be pointing to /web/app/themes/, according to the docs.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

On 2 fresh installations on 2 different machines, any theme added inside /web/app/themes cannot be seen in Appearances > Themes.

Installation process was via the Trellis docs (which assume use of Bedrock).

**Please describe your local environment:**

Bedrock version: 1.7.7

WordPress version: 4.7.4

PHP version: 7.1.4

OS: Ubuntu 16.04.2 x64

**Where did the bug happen? Development or remote servers?**

2 separate remote servers with the same above configuration.

**Comment by retlehs** [comment]
did you not commit your themes to the repo? did you not point your trellis site to use the correct repo for your site? 

this definitely works as expected. please post on https://discourse.roots.io/ with more details.

**Comment by gretzky** [comment]
Everything is committed, quadruple checked. Like I said, 2 different machines, 2 different servers.  I've done this about 30 times now and have never encountered this issue.

**Comment by simentesempre** [comment]
Same exact issue here
