### ISSUE TITLE
WP-CLI server issues

### ISSUE THREAD

**Issue by oktalk** [roots/bedrock#321]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

When running the site locally via WP-CLI server (i.e.: `wp server --host=localhost --port=8080 --config=wp-cli.yml`) all paths and links are broken.

**What is the expected or desired behavior?**

In typical Wordpress installs the `wp server` enables you to serve Wordpress locally without touching your vhost or apache.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

1. With WP-CLI installed setup your Bedrock project all the way to step three
  * You'll need to set `WP_HOME` to http://localhost:8080
  * Also us WP-CLI to install Wordpress like so: `wp core install --url=localhost --title=Site --admin_user=YOURADMIN --admin_password=YOURPASS --admin_email=info@domain.com` 
2. Instead of setting your site vhost, as you would do in step 4, run `wp server`

The site should run with all links broke (screenshot attached).

**Please describe your local environment:**

Bedrock version: latest

WordPress version: 4.8.0

PHP version: 7.0.2

OS: Mac OS Sierra

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/c/bedrock) thread or were any utilized (please link them)?**

None

---

**Other relevant information:**

WP-CLI documentation: https://developer.wordpress.org/cli/commands/server/
![screenshot-localhost-8080 2017-07-06 16-07-47](https://user-images.githubusercontent.com/158135/27933189-04b83c32-6266-11e7-91c6-375bb69c2b33.png)

**Comment by oktalk** [comment]
Ha! It looks like you can get WP-CLI working if you update the path in your `wp-cli.yml` file. When I set my path to `path: web` then run `wp server` everything works.

**Comment by oktalk** [comment]
I could PR this if you want.

**Comment by swalkinshaw** [comment]
Bedrock requires it as `web/wp` for other contexts as far as I'm aware. Unless WP-CLI got smarter about it?

**Comment by kalenjohnson** [comment]
Like swalkinshaw pointed out, `path` needs to be set to the WP folder. Perhaps try adding `--docroot=web` to the `wp server` command

**Comment by QWp6t** [comment]
I can confirm that `--docroot=web` resolves this issue.

**Comment by pioneerskies** [comment]
Being on this issue today I'd like to share that `wp-cli.yml` could be configured like

```yml
path: web/wp

server:
  docroot: web
```

and this way you can invoke a clean `wp server` command w/o other worries.

Since my dev workflow requires me to lay in the theme directory, I've put on a tricky but functional way: inside theme's folder I have another `wp-cli.yml` like this:

```yml
server:
  docroot: ../../../ # this is the web/ directory

_:
  merge: true
  inherit: ../../../../wp-cli.yml # This is bedrock's root wp-cli.yml
```

Awful but solid.
