### ISSUE TITLE
Bedrock is incompatible with WP Multisite 

### ISSUE THREAD

**Issue by REPTILEHAUS** [roots/bedrock#328]
**What is the current behavior?**

trying to access network admin on wp multisite results in 404 - running on nginx

**What is the expected or desired behavior?**

to navigate correctly

---

## Bug report

**Please describe your local environment:**

Bedrock version: latest

WordPress version: latest

PHP version: 7

OS: debian

**Where did the bug happen? Development or remote servers?**
all servers/docker containers

I tracked this down to the link-template.php file (also noted in another bug) but hardcoding the core files is not a road i want to go down - this is a shame that there is no official fix from you guys yet as it seems to be a long running bug and i would ideally love to use bedrock on all my wordpress builds.

**Comment by lekkerduidelijk** [comment]
Check out #251

**Comment by REPTILEHAUS** [comment]
Yeah tried that but it didnt work, i think you should make it very clear that it is NOT suitable for multisite. I found out the hard way.

**Comment by retlehs** [comment]
Bedrock works with multisite. Both subdomain and subdirectory installs.

**Comment by JulienMelissas** [comment]
Just want to mention many of us on the Roots team are running pretty large, mission-critical, and awesome multisite installs with Bedrock, so I can assure you it works. I'm working on 100% compatibility with this mu-plugin over here: https://github.com/roots/multisite-url-fixer. Would love your feedback on that plugin, and it's close to working with both subdomain and subdirectory installs.

**Comment by REPTILEHAUS** [comment]
Cheers man, appreciated I think I found this plugin around the time I was facing the issues. I was running nginx and narrowed the issue down to the links-template.php (or something like that) in a core file, patching it there worked, I had tried your url fixed but faced issues because i had written a hook so that all the multisites used the one image upload location, for whatever reason using your plugin made all my images disappear on certain child sites, so perhaps if I didnt have that hook it would have worked.. I wasted a lot (a hell of a lot) of hours so ended up ditching bedrock all together.

**Comment by JulienMelissas** [comment]
Understood. Might have been related to https://github.com/roots/bedrock/issues/325 tbh. I haven't had time to test it or look into it, but if you ever want help in the future feel free to use our [discourse](https://discourse.roots.io) for more specific back and forth.

**Comment by REPTILEHAUS** [comment]
No worries 👍 thanks again
