### ISSUE TITLE
Bedrock incompatible with Lando (local development environment)

### ISSUE THREAD

**Issue by elliottmangham** [roots/bedrock#332]
Hello,

I am using *[Lando](https://github.com/lando/lando)*, a growing local development environment tool that competes with AMPPS, MAMPS, Local by Flywheel, Docker, Vigrant and all of the others.

This solution is particularly great, because of it's easy setup and usage.

That said, I am having an issue when using *Bedrock* specifically - whereas standalone WordPress works perfectly.

I am unaware if this is an issue with the *Bedrock* setup, or rather an issue with Lando _(more likely)_.

Please, can you look into a fix for this?

More details can be found here: [https://github.com/lando/lando/issues/499](https://github.com/lando/lando/issues/499)

Thank you in advance!

**Comment by swalkinshaw** [comment]
This is almost certainly a Lando issue and I'm guessing there's nothing we can do in Bedrock itself.

Bedrock is really just a [subdirectory install](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory).
