### ISSUE TITLE
WP appears to be redirecting port when going to site, but not on wp-admin

### ISSUE THREAD

**Issue by samwise24** [roots/bedrock#334]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [X] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Due to my office AV I have to use port 8080 for Apache. As such, I have :8080 on the end of my WP_HOME, and when I go to the WP-admin for my site it works fine, it's connecting to the database and is fully functional. However, when I click through to the site from the dashboard _or_  just visit the url normally (with port on the end), it appears to redirect to the site url without port and as such throws up a browser 404 error. The "visit site" link in the dashboard correctly shows the url with :8080 on the end. When I try to put in the url with a different (random) port, it keeps that in the url bar on failure. For these reasons I'm sure that the site is redirecting me specifically to port 80 rather than it being any error on vhosts or such (and this hasn't occurred with any other local sites). 

I've tried a few of the highest result solutions when searching for this as a WP issue (regarding canonical redirects), but none have solved it, so I wondered if it was something you might be aware of through bedrock. 

**What is the expected or desired behavior?**

The site does not redirect to the wrong port. 

---

**Please describe your local environment:**

Bedrock version: 1.8.4

WordPress version: 4.9

PHP version: 7.1.9

OS: Windows 10

**Where did the bug happen? Development or remote servers?**

Development, Apache server

**Is there a related [Discourse](https://discourse.roots.io/c/bedrock) thread or were any utilized (please link them)?**

X

---

**Comment by retlehs** [comment]
hard to help without any details. most likely not a bug, just a configuration issue. check your environment variables, etc. / post over on https://discourse.roots.io/ with more details for support
