### ISSUE TITLE
Fatal error when installing/configuring WooCommerce-Plugin

### ISSUE THREAD

**Issue by dennzimm** [roots/bedrock#337]
**What is the current behavior?**

![screenshot-2017-12-1 https example dev](https://user-images.githubusercontent.com/12062530/33478508-d0a197fc-d689-11e7-8b0e-212eeafc5151.png)

**What is the expected or desired behavior?**

A working WooCommerce installation + be able to configure this plugin

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. Setup Trellis + Bedrock
2. Add `"wpackagist-plugin/woocommerce": "3.2.5"` to composer.json
3. composer install && update
4. Activate WooCommerce
5. Follow Setup (until Step 3)
6. Error: ![screenshot-2017-12-1 https example dev](https://user-images.githubusercontent.com/12062530/33478508-d0a197fc-d689-11e7-8b0e-212eeafc5151.png)

**Please describe your local environment:**

Bedrock version: 1.8.5

WordPress version: 4.9

PHP version: 7.1

OS: macOS High Sierra (10.13.1)

**Where did the bug happen? Development or remote servers?**

Development

**Comment by retlehs** [comment]
installing woocommerce via composer doesn’t cause a different plugin’s files to no longer exist

please use https://discourse.roots.io/ for personal support requests
