### ISSUE TITLE
File managers and bedrock access rights

### ISSUE THREAD

**Issue by unnamedfeeling** [roots/bedrock#339]
## Submit a feature request or bug report

- ✓ I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [maybe] This is a feature request
- [maybe] This is a bug report
- ✓ This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- ✓ I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

When i install any plugin that works with filesystem it will only show the contents of bedrock/web/wp and stick to that directory. I can see lower-level directories, but not the app directory of the project (bedrock/web/app). 

**What is the expected or desired behavior?**

Plugins that work with wordpress files can access only bedrock/web/app and NOT bedrock/web/wp

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

1. install bedrock
2. install any filemanager plugin (https://wordpress.org/plugins/file-manager/)
3. go to the plugin main page

**Please describe your local environment:**

Bedrock version: 1.8.2

WordPress version: 4.9.1

PHP version: 7.0.12

OS: Windows 10 Pro / Ubuntu Linux 16.04 

**Where did the bug happen? Development or remote servers?**

Both - development (Windows 10 Pro) and remote (Ubuntu Linux 16.04)

**Is there a related [Discourse](https://discourse.roots.io/c/bedrock) thread or were any utilized (please link them)?**

Could not find anything.

---

**Other relevant information:**

This problem could also affect backup plugins (such as BackUpWordpress). They all are broken due to this problem.

**Comment by retlehs** [comment]
the nice thing about bedrock is that if a plugin isn't functioning properly then there's likely something wrong on the plugin's end. please reach out to the plugin author about them properly supporting wordpress installed in a subdirectory with a custom content directory.
