### ISSUE TITLE
WPINC is not defined. Plugin causes white screen. 

### ISSUE THREAD

**Issue by connerbw** [roots/bedrock#343]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [X] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

---

Instead of:

```php
if ( ! defined( 'ABSPATH' ) ) {
	die;
}
```

Some Composer compatible plugins do this:

```php
if ( ! defined( 'WPINC' ) ) {
	die;
}
```

[Like this plugin for example](https://github.com/collizo4sky/persist-admin-notices-dismissal/issues/14). When running with Bedrock this leads to a white screen of death.

**What is the expected or desired behavior?**

`WPINC` is defined before Autoloader .

---

## Bug report

Xdebug trace:

![xdebug-trace](https://user-images.githubusercontent.com/812192/35255458-1dab84b6-ffbd-11e7-943a-957f6d43e5c5.png)

**Please describe your local environment:**

Bedrock version: https://github.com/pressbooks/bedrock
WordPress version: 4.9.2
PHP version: 7.1.12
OS: Ubuntu 16.04

**Comment by swalkinshaw** [comment]
Thanks for the detailed report. I see that the plugin you were having issues with updated their code to use `ABSPATH` which is nice.

Considering we've never had this bug report before, it seems like using `WPINC` over `ABSPATH` might be rare. I don't really know of the consequences of changing the order of requires so I'm going to leave this as is.
