### ISSUE TITLE
Using Docker as an alternative to Trellis for AWS deploying Bedrock sites

### ISSUE THREAD

**Issue by distributev** [roots/bedrock#346]
This is more of a query - How achievable is to use roots.io + Docker to achieve what is described in this project?

https://github.com/distributev/wordpress-laravel-docker-local-cloud

Any roots.io / Docker expert willing to take on this project?

**Comment by patricktruebe** [comment]
Hi @distributev my company kilenda.de is built on Woocommerce (WP) and Dokku. As we prepare a major update, we are evaluating roots.io with very promising results. We have got a working project which integrates neatly into Gitlab CI, Docker and Dokku.

Thus I'd see your request as very achievable (as we are currently doing it). I would advise to split WordPress and Laravel into different projects, as they have very different structures with some infrastructure code in common.

**Comment by retlehs** [comment]
don’t clear out the issue template... don’t use github for support.
