### ISSUE TITLE
Custom config for WP CLI

### ISSUE THREAD

**Issue by bobmulder** [roots/bedrock#356]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

---

**What is the current behavior?**

I am not able to set custom configurations or my wp-cli. I need another DB Host (since I'm using Docker) for my (out-of-the-box) `wp` command.

**What is the expected or desired behavior?**

Changing the following in `application.php`:

```
/**
 * Use Dotenv to set required environment variables and load .env file in root
 */
if (WP_CLI === true) {
  $dotenv = new Dotenv\Dotenv($root_dir, '/.env.cli');
  if (file_exists($root_dir . '/.env.cli')) {
    $dotenv->load();
    $dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL']);
  }
} else {
  $dotenv = new Dotenv\Dotenv($root_dir);  
  if (file_exists($root_dir . '/.env')) {
    $dotenv->load();
    $dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL']);
  }
}
```

This way I'm able to configure a custom `.env.cli` myself. 

I am curious how you think about this. If this is a valid way of configuring I can work this out in better code in a PR.

**Comment by mAAdhaTTah** [comment]
You might be better off using [WP-CLI aliases](https://developer.wordpress.org/cli/commands/cli/alias/) than this.

**Comment by bobmulder** [comment]
Hi @mAAdhaTTah, I don't see how WP-CLI aliases could work here for a different DB Host. Can you explain?

**Comment by aaemnnosttv** [comment]
How about just setting the dotenv vars you want to change with environment variables before running wp-cli as phpdotenv will not override vars that are already set by default.

Something like this should work:

```sh
source .env.cli && wp ...
```

If that works then you could wrap that into a bash alias or something else to remove the repetition there.

Alternatively, you could add a `require` key to your project's `wp-cli.yml` file and load your cli-specific `.env.cli` file there

E.g.

```yml
path: web/wp/
require:
  - config/cli-bootstrap.php # create this file
```

**config/cli-bootstrap.php**
```php
$root_dir = dirname(__DIR__);

if (file_exists($root_dir . '/.env.cli')) {
    require_once($root_dir . '/vendor/autoload.php');
    $dotenv = new Dotenv\Dotenv($root_dir, '/.env.cli');
    $dotenv->load();
    $dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL']);
}
```

Untested, but should work

**Comment by bobmulder** [comment]
Thank you for your suggestions. Those should work and are cleaner ways. I can implement this locally, but are you guys interested in a PR to support custom config's for the WP CLI?

**Comment by swalkinshaw** [comment]
Sorry for the very late reply on this but we aren't interested in it at this time.
