### ISSUE TITLE
Do not have /wp/ as part of the site URL?

### ISSUE THREAD

**Issue by hanoii** [roots/bedrock#358]
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

I haven't found a way or documented way to not have wp/ on the url, is that at all possible

I found #316 but he wants it because of a plugin, I just wants it because of seo and a number of ohter stuff. 

Any thoughts?

**Comment by hanoii** [comment]
Erm, I think jump too quickly into this. XClosing for now.

**Comment by amarsyla** [comment]
@hanoii I'm also having problems finding a way of using the base url without `/wp/`, were you able to find a solution?

**Comment by MWDelaney** [comment]
A standard implementation of Bedrock doesn’t have `/wp` in the URL. Please make sure you’ve [read the documentation](https://roots.io/bedrock/docs/installing-bedrock/) and searched [the forum](https://discourse.roots.io/). This question has come up a few times.

**Comment by amarsyla** [comment]
Oh, I had the WP_SITEURL and WP_HOME variables misconfigured. Thanks @MWDelaney
