### ISSUE TITLE
Provide a way to inherit from bedrock

### ISSUE THREAD

**Issue by drzraf** [roots/bedrock#360]
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

---

**What is the current behavior?**

Initial installation looks like:
```
$ composer create-project roots/bedrock
$ cp my-composer.json composer.json
$ composer update
```

**What is the expected or desired behavior?**

`$ composer create-project my-private/repository`

---

Bedrock version: 1.8.10

WordPress version: 4.9.6

PHP version: 7.2

OS: Debian

## Feature Request

**Please provide use cases for changing the current behavior:**

I want to manage WordPress themes/plugins using composer.
For that, I usually host a installation-wide `package.json` in a [private repository](https://stackoverflow.com/a/19325683/5441588) which should be a copy of https://github.com/roots/bedrock/blob/master/composer.json (enhanced with my custom `require`s).

I would rather like to avoid keeping bedrock's root under git because there is nothing to version here except `composer.json` itself:
- the directory layout of the installation, .gitkeep? composer can (re)create this as well
- `.env` | `defines`: they are usually private (outside this repository) and I auto-generate them (Ansible)

So I wonder what could be the best practices to inherit/compose from bedrock's (`repositories`, `scripts`, `extra`, `requires`) while keeping the smallest possible per-project `package.json`.

In some cases, I'd even like to be able to keep this main `package.json` as `wp-package.json` in my project's theme directory (which is always versioned)

**Other relevant information:**
```
$ git status # after bedrock's create-project && git init/add .
	new file:   .env.example
	new file:   .gitignore
	new file:   CHANGELOG.md
	new file:   CODE_OF_CONDUCT.md
	new file:   LICENSE.md
	new file:   README.md
	new file:   composer.json
	new file:   composer.lock
	new file:   config/application.php
	new file:   config/environments/development.php
	new file:   config/environments/production.php
	new file:   config/environments/staging.php
	new file:   vendor/.gitkeep
	new file:   web/app/mu-plugins/bedrock-autoloader.php
	new file:   web/app/mu-plugins/disallow-indexing.php
	new file:   web/app/mu-plugins/register-theme-directory.php
	new file:   web/app/plugins/.gitkeep
	new file:   web/app/themes/.gitkeep
	new file:   web/app/uploads/.gitkeep
	new file:   web/index.php
	new file:   web/wp-config.php
	new file:   wp-cli.yml
```

**Comment by retlehs** [comment]
please use roots discourse to ask questions and get support
