### ISSUE TITLE
Multiple .env or config files for multi site

### ISSUE THREAD

**Issue by erralb** [roots/bedrock#361]
- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [X] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

---

**What is the current behavior?**

I am using Bedrock in a multi site configuration, and I would need a specific .env or configuration files for each site. **I am not using Trellis**.

Why you ask? For an SMTP plugin where I need to add the password in the configuration file :
define( 'WPMS_SMTP_PASS', 'your_password' );

The problem is these passwords are different depending sites.

**What is the expected or desired behavior?**

Being able to create more than one .env files, or another environment file where I could define some sub site specific variables.

---

**Please describe your local environment:**

Bedrock version: Can't find the version, but like 2 weeks old.

WordPress version: 4.9.6

PHP version: 7.1

OS: Debian Stable

---

## Feature Request

Actually in the past, I had this problem already and made a quick workaround.
I added this code to the application.php :

```
if (file_exists($root_dir . '/.env.'.$_SERVER['HTTP_HOST'])) {
  Dotenv::load($root_dir,'.env.'.$_SERVER['HTTP_HOST']);
}
elseif (file_exists($root_dir . '/.env')) {
  Dotenv::load($root_dir);
}

```
Which basically checks if a .env.my-host.com file exists and if it does, loads it, but huh, not great. Then I would put my specific variables into .env.my-host.com files.

So I was wondering if there's already a way of achieving this or not. I haven't found anything about this in the Bedrock documentation for multi site.

**Comment by devkinetic** [comment]
I think that is a novel approach. Maintaining many env files sounds tedious though, especially when onboarding an environment, but like you said it does work. I have to solve this as well, I have berock env, My own env, and docker hosting env that all need to live together. I didn't even think about multisites yet...

**Comment by TangRufus** [comment]
Perphas adding `$ mv .env.XYZ .env` to the deploy script is sufficient?

**Comment by erralb** [comment]
"Maintaining many env files sounds tedious though"
True that. 

But in the end, I find that when using multisite, you often need to make specific configurations on a per site basis. In my use cases, I would not create a sub-site everyday, so having to create a new .env file once in a while, which I would mostly never touch afterwards has worked fine for me.

In the end there is a couple of ways of achieving various config or .env files for multisite, when I asked this I was just wondering if they could be some sort of standard way!

**Comment by cfoellmann** [comment]
You can define environment variables in your php-fpm config per your vhost. Would that be an option for you?

**Comment by erralb** [comment]
This was a feature request for a "standard way" for achieving this, but the solution I implemented loading different .env files is working for me.
Anything would work for me :-) I was more asking core developers how they would go about it!

**Comment by QWp6t** [comment]
My suggestion would be to use sunrise.php since it will have the $site_id that you could use to reference each site. You could also use the site's slug or something if you wanted, but I figure for something like this, there's no need to get too fancy.

So maybe something like this...

**/bedrock/config/sites/\<id\>/.env**
```
# your config
```

**/bedrock/config/application.php**
```php
define('SUNRISE', true);
```

**/bedrock/web/app/sunrise.php**
```php
$dotenv = Dotenv\Dotenv::create("{$root_dir}/config/sites/{$site_id}");
define('WPMS_SMTP_PASS', env('WPMS_SMTP_PASS'));
// etc.
```
