### ISSUE TITLE
mu-plugins and .gitignore

### ISSUE THREAD

**Issue by palmiak** [roots/bedrock#367]
## Submit a feature request or bug report

- [ x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [ x ] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [ x ] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

When using Bedrock via `git clone` (and then removing the .git and adding this to own repo) Bedrock's mu-plugins aren't added to the new git repo. 

**What is the expected or desired behavior?**

It works as it should but I think I would be better/safer if there was a `mu-plugins/bedrock-plugins` folder and it would be removed from .gitignore (to be sure that those plugins are always present).

---

**Comment by roots-ladybug** [comment]
Hi @palmiak,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by palmiak** [comment]
I've corrected the issue by adding the issue template.

**Comment by swalkinshaw** [comment]
I'm confused about the issue here...

```bash
$ git clone git@github.com:roots/bedrock.git bedrock-test
Cloning into 'bedrock-test'...
remote: Counting objects: 1287, done.
remote: Total 1287 (delta 0), reused 0 (delta 0), pack-reused 1287
Receiving objects: 100% (1287/1287), 339.16 KiB | 3.50 MiB/s, done.
Resolving deltas: 100% (638/638), done.
$ cd bedrock-test
$ rm -rf .git
$ git status
fatal: not a git repository (or any of the parent directories): .git
$ git init .
Initialized empty Git repository in /Users/scott/dev/bedrock-test/.git/
$ git add .
$ git commit -a
[master (root-commit) d599686] asfd
 28 files changed, 1499 insertions(+)
 create mode 100644 .editorconfig
 create mode 100644 .env.example
 create mode 100644 .gitattributes
 create mode 100644 .github/CONTRIBUTING.md
 create mode 100644 .github/ISSUE_TEMPLATE.md
 create mode 100644 .gitignore
 create mode 100644 .travis.yml
 create mode 100644 CHANGELOG.md
 create mode 100644 CODE_OF_CONDUCT.md
 create mode 100644 LICENSE.md
 create mode 100644 README.md
 create mode 100644 composer.json
 create mode 100644 composer.lock
 create mode 100644 config/application.php
 create mode 100644 config/environments/development.php
 create mode 100644 config/environments/production.php
 create mode 100644 config/environments/staging.php
 create mode 100644 phpcs.xml
 create mode 100644 vendor/.gitkeep
 create mode 100644 web/app/mu-plugins/bedrock-autoloader.php
 create mode 100644 web/app/mu-plugins/disallow-indexing.php
 create mode 100644 web/app/mu-plugins/register-theme-directory.php
 create mode 100644 web/app/plugins/.gitkeep
 create mode 100644 web/app/themes/.gitkeep
 create mode 100644 web/app/uploads/.gitkeep
 create mode 100644 web/index.php
 create mode 100644 web/wp-config.php
 create mode 100644 wp-cli.yml
```

**Comment by palmiak** [comment]
Sorry - I wasn't clear enough.

Steps to replicate:
1. `git clone git@github.com:roots/bedrock.git bedrock-test`
2. `cd bedrock-test`
3. `rm -rf .git` - becuase I want to use Bedrock as base of new project
4. `git init`, `git add *` and `git commit`

You will see that files from `mu-plugins` are not in the new repo.

To fix this - I think that the best way it would be to change the folder structure a bit https://github.com/palmiak/bedrock/tree/mu-plugins

I moved all the Bedrock's `mu-plugins` to one folder and changed `.gitignore` a bit to be sure that it's **always** in the repository.

**Comment by swalkinshaw** [comment]
Still confused 😛 

Your steps were the exact same as mine?

```$ git clone git@github.com:roots/bedrock.git bedrock-test
$ cd bedrock-test
$ rm -rf .git
$ git init .
$ git add .
$ git commit -a
```

**Comment by austinpray** [comment]
Brother `git add *` is not the same as `git add .`

`git add .` adds all files in the directory recursively

**Comment by palmiak** [comment]
that did the trick - thanks guys.
