### ISSUE TITLE
W3 Total Cache and /app/plugins/

### ISSUE THREAD

**Issue by benjibee** [roots/bedrock#38]
The first plugin often installed in many Wordpress setups is [W3 Total Cache](http://wordpress.org/plugins/w3-total-cache/).

This plugin creates  `app/cache/` and `app/w3tc-config/` directories outside of the `app/plugins/` directory in addition to three other files used by the plugin: `advanced-cache.php`, `db.php`, and `object-cache.php`.

Perhaps adding plugin-specific ignores to Bedrock is a bit much, but maybe a line about this is the readme would be a good idea?

From `README.md`:

> plugins, and mu-plugins are Git ignored by default since Composer manages them

As of now, it seems to suggest that all plugins will be placed into the `/app/plugins/` directory and be contained there, kept in check via Composer without any additional configuration of Bedrock's files.

**Comment by marshmallowcreme** [comment]
Why not just move the configuration files to the shared directory?

**Comment by etcook** [comment]
@marshmallowcreme There's more to it than just symlinking the generated config file (which, correct me if I'm wrong, would still probably be considered at odds with "12 Factor")

**Comment by swalkinshaw** [comment]
configs definitely should not be shared. They are code as well and need to
remain atomic in case of rollbacks.

**Comment by marshmallowcreme** [comment]
I can understand that. For me, it suffices to make those configs shared
since I don't expect them to change dramatically between deploys.

I'm curious, though - what are you guys using for caching instead of W3TC?

**Comment by etcook** [comment]
@marshmallowcreme Varnish. I believe some are using batcache and memcached.

**Comment by tommymarshall** [comment]
For anyone else viewing this: We're using W3 Total Cache and, since our caching on staging and production is the same, we simply symlinked the cacheing-related files and directories in our deploy.rb:
```ruby
set :linked_files, fetch(:linked_files, []).push(
  '.env',
  'web/app/advanced-cache.php',
  'web/app/db.php',
  'web/app/object-cache.php'
)
set :linked_dirs, fetch(:linked_dirs, []).push(
  'web/app/uploads',
  'web/app/cache',
  'web/app/w3tc-config'
)
```

Worked without a hitch.
