### ISSUE TITLE
Plugin which works on classic WordPress doesn't work on Bedrock

### ISSUE THREAD

**Issue by distributev** [roots/bedrock#407]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

I'm using a plugin which works just fine on a classic WordPress installation (i.e. SiteGround)

When I install the same plugin on a Bedrock WordPress installation it does not work and it gives all kind of cryptic messages.

I followed both of the installation processes described here and both ends with failure.

https://wperp.com/docs/erp-core/installation/

**What is the expected or desired behavior?**

Things which work fine on classic WordPress should work fine on Bedrock WordPress too.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

Just install bedrock and then try to install wp-erp and you will see it is not working.

https://wperp.com/docs/erp-core/installation/

**Please describe your local environment:**

Bedrock version: latest Bedrock

WordPress version: latest WordPress

PHP version:

OS:

**Where did the bug happen? Development or remote servers?**

X

**Is there a related [Discourse](https://discourse.roots.io/c/bedrock) thread or were any utilized (please link them)?**

X

---

## Feature Request

(delete this section if not applicable)

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by MWDelaney** [comment]
Can you please provide some examples of the cryptic messages the plugin produces when installed in a Bedrock environment?

**Comment by swalkinshaw** [comment]
Also see https://roots.io/bedrock/docs/bedrock-compatibility/

**Comment by distributev** [comment]
Here you can find more details

https://github.com/wp-erp/wp-erp/issues/753
