### ISSUE TITLE
Change composer.json indent to 4 spaces

### ISSUE THREAD

**Issue by rodrigoaguilera** [roots/bedrock#409]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)

---

**What is the current behavior?**

The composer.json file is indentended with 2 spaces

**What is the expected or desired behavior?**

Follow the default standard of 4 spaces, the same as composer.lock

---

**Comment by TangRufus** [comment]
Suggestion: Use [composer-normalize](https://github.com/localheinz/composer-normalize) so that formatting `composer.json` can be automated

**Comment by rodrigoaguilera** [comment]
I think that can be a followup to this issue. I completely agree about adding that plugin

**Comment by retlehs** [comment]
> Follow the default standard of 4 spaces

there's not a standard for spacing on composer files

the standard for roots projects is using 2 spaces for json
