### ISSUE TITLE
Can't seem to deploy with capistrano3... but all responses are successful.

### ISSUE THREAD

**Issue by jfrux** [roots/bedrock#41]
```
$ cap production deploy
 INFO [e9cd1232] Running /usr/bin/env mkdir -p /tmp/my_app/ on my_app.com
 INFO [e9cd1232] Finished in 0.484 seconds with exit status 0 (successful).
 INFO Uploading /tmp/my_app/git-ssh.sh 100.0%
 INFO [e91dcfcd] Running /usr/bin/env chmod +x /tmp/my_app/git-ssh.sh on my_app.com
 INFO [e91dcfcd] Finished in 0.063 seconds with exit status 0 (successful).
```

This all looks good, but it doesn't create the directories or anything.

**Comment by joshuairl** [comment]
Since this is top result for google... figured I'd post this other thing that helped resolve my issues for some strange reason...

added:
```ruby
set :composer_install_flags, '--no-dev --no-interaction --optimize-autoloader'
```
by removing the `--quiet` from the default install flags it helped resolve it... must have given capistrano what it needed to ensure it completed correctly...
