### ISSUE TITLE
.env with quoted values keeps the quotes when DEFINE'ing.

### ISSUE THREAD

**Issue by jawngee** [roots/bedrock#416]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [X] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

I just did a fresh setup of the latest trellis + bedrock.

If the .env file has quoted values, eg:

```
DB_NAME='database_name'
DB_PASSWORD='example_dbpassword'
DB_USER='database_user'
```

Those values are defined in WordPress **WITH** the single quotes which is causing WordPress to fail to load.

The .env is generated by trellis/ansible with the single quotes, so I'm guessing the issue is with Bedrock's config loading stuff.

**What is the expected or desired behavior?**

The .env values are DEFINE'd without quotes.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Literally all I did to reproduce:

- Clone trellis
- Clone bedrock
- Set the domain/site names in the development group_vars
- Vagrant up

**Please describe your local environment:**

Bedrock version: cfb68e1

WordPress version: 5.0.3

PHP version: 7.3

OS: Ubuntu 18.0something

**Where did the bug happen? Development or remote servers?**

Local development image

**Comment by jawngee** [comment]
Updated phpdotenv to 3.3.6 fixes the issues.

**Comment by retlehs** [comment]
i'm not seeing a 3.3.6 tag? https://github.com/vlucas/phpdotenv/releases

**Comment by jawngee** [comment]
Sorry I meant 3.3.2

**Comment by retlehs** [comment]
not sure why i can't re-produce, but the dependency has been bumped: #417
