### ISSUE TITLE
Menu links not well formed in multisite installation

### ISSUE THREAD

**Issue by marcgenou** [roots/bedrock#418]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/bedrock/issues)
- [x] I've read the [docs](https://roots.io/bedrock/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Multisite installation network menu links dont work because base url is missing

**What is the expected or desired behavior?**

network links working and built as usual in side menu
---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

Multisite installation with nginx and using url fixer plugin provided. config/application changes done, only those two changes and everything else seems working great, but cannot access new site or network menus due to this "bug"

http://192.168.1.100/wp/wp-admin/my-sites.php as a sample what is formed in side menu
http://wp/wp-admin/network/ as a sample of url formed in above menu

**Please describe your local environment:**

vagrant, centos 7, nginx, php 7.2, composer

Bedrock version: last week

WordPress version: 5.0.3

PHP version: 7.2.14

OS: centos 7

**Where did the bug happen? Development or remote servers?**

development

**Comment by rdanusha** [comment]
Same issue here.. any updates ???

**Comment by rdanusha** [comment]
Install multisite-url-fixer plugin. do not put it on the mu-plugins folder. 
https://github.com/roots/multisite-url-fixer
