### ISSUE TITLE
wikimedia/composer-merge-plugin for easier bedrock updates

### ISSUE THREAD

**Issue by drzraf** [roots/bedrock#433]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

I suggest bedrock `composer.json` depends upon `wikimedia/composer-merge-plugin` to provide an easier and clean extensibility method.

## Motivation

_bedrock_ is used as a boilerplate from which one creates WordPress plugins/themes set.
The main (if not sole) modification ever done is probably inside `composer.json`.
But changes from bedrock (mostly WP releases) are subject to small `composer.json` merges in the `requires` section. While that's the point of a boilerplate, that's a small (avoidable) annoyance.
`wikimedia/composer-merge-plugin` could limit, if not avoid, that.

## Additional context

`wikimedia/composer-merge-plugin` provides a way for `composer` to include external `composer` section which are merged inside the main one.

Example of suggested modifications:
```diff
--- a/composer.json
+++ b/composer.json
@@ -39,7 +39,8 @@
     "oscarotero/env": "^1.1.0",
     "roots/wordpress": "5.2",
     "roots/wp-config": "1.0.0",
-    "roots/wp-password-bcrypt": "1.0.0"
+    "roots/wp-password-bcrypt": "1.0.0",
+    "wikimedia/composer-merge-plugin": "dev-master"
   },
   "require-dev": {
     "squizlabs/php_codesniffer": "^3.0.2",
```

And adding a default `extra` section:
```js
    "merge-plugin": {
      "replace": true,
      "merge-extra": true,
      "include": [
        "bedrock-ext-*.json"
      ],
      "recurse": false
    }
```

That way, one would just build it's bedrock _flavor_ by add its composer files named `bedrock-ext-*.json`. No conflict/merge when upstream is updated.

**Comment by oxyc** [comment]
> If anything I'd think Bedrock's default composer.json should contain nothing and we specify our own requirements in an extension config? That might ruin the merge functionality though if it takes precendence.

This is what Drupal's BLT tool used to do, they had `composer.required.json` merged into the projects own `composer.json` _(BLT is a bit like bedrock for Drupal but maintained by Acquia which is Drupal's version of Automattic)._

From their perspective, even if it might not be as relevant to bedrock, BLT decided to eventually [remove the merge plugin](https://github.com/acquia/blt/issues/2744) because of issues together with other composer plugins such as https://github.com/cweagans/composer-patches (more relevant to Drupal which pretty much relies on patches for a project).

**Comment by swalkinshaw** [comment]
Closing this since it's unlikely we'll ever implement this.
