### ISSUE TITLE
Translation of Gutenberg Plugin missing when using Bedrock

### ISSUE THREAD

**Issue by Furo42** [roots/bedrock#438]
Most of the translations in the backend of the block editor are missing when using Bedrock Boilerplate together with Gutenberg Plugin.
The translations were installed correctly.

A similiar problem was described in this topic and marked as fixed.
https://core.trac.wordpress.org/ticket/45528
**Also this Bug happens only when using the separate Gutenberg Plugin**. There is no problem when using the block editor in Wordpress 5.2.1.
This bug also appears only in Bedrock. If I define a custom wp-content in a standard WordPress installation the translations were shown correctly.
If I deactivate the part where wp-content custom directory is defined in Bedrock (in the applications.php) the translations are also there.

The Gutenberg Plugin is nearly fully translated in German. So the translations should show up. The best indicator is the string "Status and Visbility" at the right sidebar which should be "Status und Sichtbarkeit" in German.

![bedrock_bug](https://user-images.githubusercontent.com/51162201/59149107-b6f38300-8a11-11e9-927a-b947311fd0ae.jpg)

To reproduce

1. Install WordPress with Bedrock
2. Use a different language than English
3. Install Gutenberg Plugin with Composer or within the WP-Admin and activate it
4. Install the Translations
5. Create a new Post
6. The Blocks and the Boxes on the right Sidebar are shown in English

Desktop:
OS: Windows
Browser Chrome 74, Firefox 67

Tested with:
- Wordpress 5.2.1
- Gutenberg Version 5.7.0 and 5.8.0
- Bedrock 1.12.6

**Comment by roots-ladybug** [comment]
Hi @Furo42,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by retlehs** [comment]
https://roots.io/bedrock/docs/bedrock-compatibility/

**Comment by retlehs** [comment]
closing because https://github.com/WordPress/gutenberg/issues/15889 already exists and there shouldn't be anything in bedrock that could possibly cause this

**Comment by Furo42** [comment]
Short comment to this issue: I updated bedrock to the latest version and now the translations are available. I used Bedrock v1.12.8 formlery.

**Comment by strarsis** [comment]
So I updated to latest Bedrock (1.12.8), also updated to latest Gutenberg plugin (6.4.0) and WordPress (5.2.3). But the translations in Gutenberg editor are still missing.

@Furo42: Are you using Bedrock directly from master or 1.12.8 release tag?

**Comment by strarsis** [comment]
@Furo42: Just tried bedrock from `dev-master`. Still no translations for Gutenberg editor.

**Comment by Furo42** [comment]
@strarsis I'm using the latest Bedrock release (1.12.8), not the dev-master. Sorry, there was a typo in my last comment. I used v1.7.3 formlery.

I know it's a dumb question but did you also installed the translations for Gutenberg through the dashboard?

**Comment by Furo42** [comment]
@strarsis That's strange. I installed Gutenberg and downloaded the language files through the dashboard. The `json` files are called e.g. `gutenberg-de_DE-2db29b02b406fc710377e5966a268a5b.json` and their location is at `web/app/languages/plugins`.
If I remove the json files from Gutenberg the most strings will be not translated.

Does this problem only happens with Gutenberg? Did you try to install another plugin with translations?
Do you have any modifications in your Bedrock config?
That's how I solved this problem: I set up a blank Bedrock project and saw that it worked fine.

**Comment by strarsis** [comment]
@Furo42: The other `json` files are missing a prefix, too.
Yes, I should set up a blank Bedrock project and install Gutenberg and its translation there.

**Comment by strarsis** [comment]
@Furo42: So I set up a new bedrock site and first it appeared to be working.
But then I noticed it only works with non-formal German (de_DE), 
but not with formal German (de_DE_formal).
Only with de_DE the `json` files are downloaded into `languages/plugins/`.

**Comment by Furo42** [comment]
@strarsis okay that's interessting. I don't know if I'm using non-formal or formal German in this project. I'll check this on monday.

**Comment by Furo42** [comment]
@strarsis "Good" News! I could reproduce the issue. If I change the language of WordPress to `de_DE_formal` Gutenberg's translations are not loading.

I also did a few more tests: I setup a non-bedrock system with `de_DE_formal` as language and installed Gutenberg. It's the same result. So it's obviously **not** Bedrock related but a bug in Gutenberg. I'll open a new issue in there.
