### ISSUE TITLE
Modify application.php to support hosts that uses non-standard mysql ports

### ISSUE THREAD

**Issue by carl-alberto** [roots/bedrock#451]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary
Some hosts uses non-standard mysql ports and there are no way to use it out of the box without modifying the application.php file

## Motivation

This allows users to append a port in the mysql define whenever the port value is present in the .env file

**Comment by aaemnnosttv** [comment]
This seems unnecessary. Can't the port be set as part of `DB_HOST` ?

It can definitely be set using the new `DATABASE_URL` connection string alternative added in #414
