### ISSUE TITLE
Env file does not parse password with # properly

### ISSUE THREAD

**Issue by Griefchief** [roots/bedrock#469]
[x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
 [x] This request isn't a duplicate of an existing issue
 [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
 [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

.env files do not parse a password with # in it properly. This gets parsed as the start of a comment, cutting of the password.

## Steps to reproduce

1. Set mysql db password to have # in it
2. add password to DB_PASSWORD field in .env
DB_PASSWORD=SomePass#Comment
3. refresh wordpress website, wordpress wp-db will complain.
![image](https://user-images.githubusercontent.com/5757704/65732889-3cd43080-e0cc-11e9-8c32-8a19d2ab134d.png)

**Expected behavior:** [Parse password properly or more realistically warn with a comment above to either escape the # if possible, or to not use #. I could not escape it...]

**Actual behavior:** [can't connect to db, see image above]

**Reproduces how often:** [100%]

## Versions

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.

## Additional information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by swalkinshaw** [comment]
Does quoting the value work?

```
DB_PASSWORD="SomePass#Comment"
```

**Comment by Griefchief** [comment]
It does work. 

This can be nasty to debug, took me 2hrs and changing wp-db.php to echo the pass... I'd suggest a warning comment in env file if you think it's applicable.

**Comment by swalkinshaw** [comment]
Closed by https://github.com/roots/bedrock/pull/471
