### ISSUE TITLE
Wrong redirected URL when installing new WordPress bedrock 1.13.0

### ISSUE THREAD

**Issue by nhanledev** [roots/bedrock#493]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When installing new WordPress with latest Bedrock version 1.13.0, the redirected URL to installation page is wrong, which is *http://domain/WP_HOME/wp/wp-admin/install.php*

![image](https://user-images.githubusercontent.com/28459250/74900427-55721980-53d2-11ea-980d-946843de148b.png)

If I change the URL to the right one which is *http://domain/wp/wp-admin/install.php*, all assets such as JS or CSS files' URLs are wrong.

![image](https://user-images.githubusercontent.com/28459250/74900513-a3871d00-53d2-11ea-9905-18b1101b40e1.png)

## Steps to reproduce

1. Clone bedrock from github
2. Run composer install
3. Access the bedrock to install new WordPress/BedRock instance

**Expected behavior:** Redirected to domain/wp/wp-admin/install.php

**Actual behavior:** Redirected to domain/WP_HOME/wp/wp-admin/install.php

**Reproduces how often:** 100%

## Versions

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.

BedRock 1.13.0

## Additional information

I believe that the behavior is from phpdotenv v4 because I have tried to upgrade to this version before, but it went crazy and I could not handle it.

**Comment by austinpray** [comment]
Not seeing this with this testbed: https://github.com/austinpray/bedrock-testbed/tree/br-493

How exactly are you running this locally?

**Comment by austinpray** [comment]
Ah never mind I can reproduce this by using the .env.example provided in the repo

![image](https://user-images.githubusercontent.com/2192970/74903343-46f21680-536e-11ea-997b-85fe4e0fa5d6.png)

https://github.com/austinpray/bedrock-testbed/tree/br-493-reproduced

[working vs not working](https://github.com/austinpray/bedrock-testbed/compare/br-493...br-493-reproduced)

**Comment by austinpray** [comment]
@nhanledev see if this fixes your issue https://github.com/roots/bedrock/pull/494, it does for me

**Comment by nhanledev** [comment]
@austinpray I can confirm that changing from a single quote to double-quote of WP_HOME in `.env` file fixes this issue.

**Comment by austinpray** [comment]
Sweet! Tagged a bugfix release https://github.com/roots/bedrock/releases/tag/1.13.1

**Comment by ali-awwad** [comment]
On Azure Web Apps this issue persists, this is because the environment variables are defined in the "Application Settings", so there is no way to add single qoutes or double qoutes. 

so my only option was just to write the full domain twice, like `WP_HOME=http://example.test` and `WP_SITEURL=http://example.test/wp` 

Also, for some reason the Azure web app does not like the salt keys to have curly brackets and other symbols, so i wrote them with only numbers and letters and few symbols .
