### ISSUE TITLE
Offload Media Lite does not work using bedrock

### ISSUE THREAD

**Issue by runningman84** [roots/bedrock#496]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

It looks like bedrock changes some logic of the file uploads. In a plain wordpress installation the offload media plugin works just fine.

## Steps to reproduce

1. Install offload media lite plugin ("wpackagist-plugin/amazon-s3-and-cloudfront":"2.3.2")
2. Activate and configure plugin
3. Upload Media file

**Expected behavior:** [What you expect to happen]
This media file should be uploaded to aws s3. The file should contain attributes for Storage Provider: Amazon S3 and other S3 related attributes.

**Actual behavior:** [What actually happens]
The file path is something like /app/uploads/filename

**Reproduces how often:** [What percentage of the time does it reproduce?]
every time

## Versions

wordpress version 5.3.2
offload media plugin 2.3.2

## Additional information

The wordpress setup runs in k8s. Which means it is important to store all media uploads in s3 instead of local files.

**Comment by swalkinshaw** [comment]
> It looks like bedrock changes some logic of the file uploads. In a plain wordpress installation the offload media plugin works just fine.

We don't change any uploads logic.

See https://roots.io/bedrock/docs/bedrock-compatibility/ for more details on plugin compatibility.

**Comment by unfrgivn** [comment]
@runningman84 I have no issue running Bedrock with offload media lite v2.3.2. That is the exact setup we run on all our sites in both a standard LAMP local, production and also in docker/k8s nginx + php-fpm environments.

For the Offload Media Lite settings, all the storage / rewrite settings are enabled and the path is set to `uploads`

**Comment by runningman84** [comment]
It looks like the problem was caused by a missing image magic and gd extension. It works fine now...
