### ISSUE TITLE
env function collide with illuminate/support

### ISSUE THREAD

**Issue by marmorag** [roots/bedrock#515]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

`env` function is colliding with `illuminate/support`.

The function `env` is redefined in package `illuminate/support` which is a dependency of `ilab/ilab-media-tools`, the issue is that the `env` function from `illuminate/support` is defined first and cause:

```
Uncaught Error: Class 'Dotenv\Environment\Adapter\EnvConstAdapter' not found in /var/www/html/vendor/illuminate/support/Env.php:67
```

## Steps to reproduce

1. `composer create-project roots/bedrock bedrock`
2. `composer require ilab/ilab-media-tools`
3. you get the error

**Expected behavior:** No error

**Actual behavior:** Class not found exception

**Reproduces how often:** 100%

## Versions

At least `1.13.4` I did not test with other version 
Reproducer on Ubuntu 18.04, and Debian 10 for original issue

## Additional information

You can find a reproducer [on this repository](https://github.com/marmorag/bedrock-ilabmedia-reproducer) a "fix" is on branch `fix` and [there's the PR](https://github.com/roots/bedrock/pull/516)

**Comment by TangRufus** [comment]
Fixed in #530

Thanks for reporting
