### ISSUE TITLE
Add a mu-plugin to disable `wp-autoupdates` by filters

### ISSUE THREAD

**Issue by tangrufus** [roots/bedrock#526]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

Add a mu-plugin to disable `wp-autoupdates` by filters

See: https://github.com/WordPress/wp-autoupdates/pull/112

**Comment by retlehs** [comment]
since we set `AUTOMATIC_UPDATER_DISABLED` to true, it looks like we don't need to do anything here?

per @joshuafredrickson on roots slack:

```php
// Disable plugins auto-update UI elements.
add_filter('plugins_auto_update_enabled', '__return_false');
// Disable themes auto-update UI elements.
add_filter('themes_auto_update_enabled', '__return_false');
```

is not necessary on a bedrock install, and

> it removes the auto-update ui elements as well

i might be mis-understanding this issue though
