### ISSUE TITLE
Do We able to use Wordpress Constants If Yes How

### ISSUE THREAD

**Issue by ksaltik** [roots/bedrock#527]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Do We able to use Wordpress Constants If Yes How 
Example
define( 'UPLOADS', 'blog/wp-content/uploads' );
define( 'UPLOADS', 'blog/wp-content/media' );
define( 'UPLOADS', 'blog/wp-content/vault' );  ....

## Motivation

Further customization of the directory structure.

**Comment by swalkinshaw** [comment]
Yes, you can set any constant by doing `Config::define('UPLOADS, 'blog/wp-content/vault')` for example.
