### ISSUE TITLE
Need to define FS_METHOD to allow module installs via admin

### ISSUE THREAD

**Issue by LTSCommerce** [roots/bedrock#557]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

In development mode, I needed to also define FS_METHOD to direct in order to install modules

## Steps to reproduce

1. Install bedrock
2. Run in devleoper mode
3. Try to install sometihng from admin
4. See error in console `Unable to connect to the filesystem. Please confirm your credentials`

**Expected behavior:** [What you expect to happen]

It works

**Actual behavior:** [What actually happens]

error in console `Unable to connect to the filesystem. Please confirm your credentials`

**Reproduces how often:** [What percentage of the time does it reproduce?]

All the time

## Versions

1.14.4

## Additional information

Proposed fix:

```
--- a/config/environments/development.php
+++ b/config/environments/development.php
 
 // Enable plugin and theme updates and installation from the admin
 Config::define('DISALLOW_FILE_MODS', false);
+Config::define('FS_METHOD', 'direct');
```
Happy to create a PR if this is an acceptable change

**Comment by retlehs** [comment]
thank you for the issue! we don't really recommend using the wp-admin for this sorta thing, but `Config::define('FS_METHOD', 'direct');` isn't necessary on the local dev env i just tried (using trellis)

feel free to add this as you need to, but this isn't something we want to include in bedrock out of the box
