### ISSUE TITLE
oscarotero/env v2.1.0 Class 'Env' not found

### ISSUE THREAD

**Issue by albertonieto** [roots/bedrock#559]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

I have recently updated composer and got the oscarotero/env v2.1.0 package. Since then I keep getting this error:

`Fatal error: Uncaught Error: Class 'Env' not found in /myproject/config/application.php:6`

## Steps to reproduce

1. Update composer to v2.1.0 on package oscarotero/env
2. Check your local repository

**Expected behavior:** [What you expect to happen]

Expected to run site normally.

**Actual behavior:** [What actually happens]

Throws error `Fatal error: Uncaught Error: Class 'Env' not found in /myproject/config/application.php:6`

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

## Versions

oscarotero/env v2.1.0

## Additional information

This is the content of the referenced file, where `Env::init()` corresponds to line 6:

```
<?php

$root_dir = dirname(__DIR__);
$webroot_dir = $root_dir . '/public';

Env::init();

// Use Dotenv to set required environment variables and load .env file in root
$dotenv = new Dotenv\Dotenv($root_dir);
if (file_exists($root_dir . '/.env')) {
    $dotenv->load();
    try {
      $dotenv->required('DATABASE_URL')->notEmpty();
    } catch (Exception $e) {
      $dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL']);
    }
}
```

It seems as if the package were not loaded since the Env Class doesn't load. Ideas?

**Comment by TangRufus** [comment]
Patch Bedrock with the https://github.com/roots/bedrock/tree/master/ branch, https://github.com/roots/bedrock/pull/530/ to be specific.

**Comment by albertonieto** [comment]
> Patch Bedrock with the [master](https://github.com/roots/bedrock/tree/master/) branch, #530 to be specific.

Sounds good! How can I do that?

**Comment by TangRufus** [comment]
Download https://patch-diff.githubusercontent.com/raw/roots/bedrock/pull/530.diff and `$ git apply` it.
However, depends on how much change you made and how "out of sync" your code is, it might not work.
For a small patch like #530, manually copy and paste the changes might be easier.

Props to @austinpray

**Comment by albertonieto** [comment]
Thanks, that was helpful. I have indeed manually added the missing parts. This is how the edited file looks like now:

```
<?php

use function Env\env;

// Directory containing all of the site's files
$root_dir = dirname(__DIR__);
$webroot_dir = $root_dir . '/public';

// Use Dotenv to set required environment variables and load .env file in root
$dotenv = Dotenv\Dotenv::createImmutable($root_dir);

if (file_exists($root_dir . '/.env')) {
    $dotenv->load();
    **var_dump(env('DB_USER'));exit;**
    try {
      $dotenv->required('DATABASE_URL')->notEmpty();
    } catch (Exception $e) {
      $dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL']);
    }
}
```

The problem I am facing is that if I var_dump the env variables I get empty values. Because of that, my msqli is not connecting to the database. Any idea?

**Comment by chesio** [comment]
@albertonieto What version of vlucas/phpdotenv are you using? I have to update the bootstrap code when I've upgraded from version 4 to 5.

Also see this issue: https://github.com/oscarotero/env/issues/8

I ended adding this to the top of the bootstrap file:
```php
\Env\Env::$options |= \Env\Env::USE_ENV_ARRAY;
```

**Comment by albertonieto** [comment]
I am using the latest version `"vlucas/phpdotenv": "^5.2",`

Sorry, when you mention the bootstrap file, which file are you referring to? I would like to try that as well.

**Comment by chesio** [comment]
Sorry, I meant `config/application.php` - it now looks like this in my Bedrock-based project (the top part):

```php
<?php

/**
 * Expose global env() function from oscarotero/env
 */
use function Env\env;

/**
 * Instruct Env\Env to read environment variables via $_ENV instead of getenv().
 * The latter does not work with DotEnv 5 by default, see: https://github.com/oscarotero/env/issues/8
 */
\Env\Env::$options |= \Env\Env::USE_ENV_ARRAY;

/** @var string Directory containing all of the site's files */
$root_dir = dirname(__DIR__);

/** @var string Document Root */
$webroot_dir = $root_dir . '/web';

/**
 * Use Dotenv to set required environment variables and load .env file in root
 */
$dotenv = \Dotenv\Dotenv::createImmutable($root_dir);
if (file_exists($root_dir . '/.env')) {
    $dotenv->load();
    $dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL']);
}

...
```

**Comment by albertonieto** [comment]
Thanks. I have added the instruction as you referred. I am able to see the env variables when I var_dump them, however my mysqli is still not connecting:

```
<?php

use Roots\WPConfig\Config;
use function Env\env;

\Env\Env::$options |= \Env\Env::USE_ENV_ARRAY;

$root_dir = dirname(__DIR__);
$webroot_dir = $root_dir . '/public';

$dotenv = \Dotenv\Dotenv::createImmutable($root_dir);
if (file_exists($root_dir . '/.env')) {
    $dotenv->load();

    Config::define('DB_NAME', env('DB_NAME'));
    Config::define('DB_USER', env('DB_USER'));
    Config::define('DB_PASSWORD', env('DB_PASSWORD'));
    Config::define('WP_HOME', env('WP_HOME'));
    Config::define('WP_SITEURL', env('WP_SITEURL'));
    var_dump(env('DB_NAME'));
    var_dump(env('DB_USER'));
    var_dump(env('DB_PASSWORD'));
    var_dump(env('WP_HOME'));
    var_dump(env('WP_SITEURL'));

    $dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL']);
}
```

I still get the:

```
Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in /myproject/public/cms/wp-includes/wp-db.php on line 1635
No such file or directory
Error establishing a database connection
```

I am very confused.

**Comment by chesio** [comment]
@albertonieto Are you sure you have `Config::apply();` at the end of the file as well? See: https://github.com/roots/bedrock/blob/master/config/application.php#L123 AFAIK, this is where the actual constants are defined. `Config::define(...);` calls are just part of internal setup, but do not actually define any constants.

**Comment by albertonieto** [comment]
Sorry about that, I was missing the apply at the end of the file. I have managed to actually connect via mysli now. I noticed however that our theme is using a `/public/content/themes/mytheme/inc/assets.php` file that reads as follows:

```
<?php

  define('ASSETS_REVISION_FILE', dirname(dirname(ABSPATH)) . '/REVISION');
  define('ASSETS_REVISION', substr(trim(@file_get_contents(ASSETS_REVISION_FILE)), 0, 12));
  define('ASSETS_PATH', dirname(dirname(ABSPATH)) . DIRECTORY_SEPARATOR . env('ASSETS_COMPILE'));
  define('ASSETS_DIRECTORY', str_replace(dirname(ABSPATH), '', ASSETS_PATH));
  define('ASSETS_HOST', env('ASSETS_HOST') ? env('ASSETS_HOST') : '//' . $_SERVER['SERVER_NAME']);
  //define('ASSETS_VERSION', ASSETS_REVISION ? ASSETS_REVISION : time('U'));
  define('ASSETS_VERSION', ASSETS_REVISION ? ASSETS_REVISION : time());

  function asset_path($path) {
    return ASSETS_HOST . ASSETS_DIRECTORY . '/' . $path . '?v=' . ASSETS_VERSION;
  }
```

I am getting a `Call to undefined function env()` for line 5. Any idea for that fix?

**Comment by chesio** [comment]
> I am getting a `Call to undefined function env()` for line 5. Any idea for that fix?

You have to add `use function Env\env;` to this file as well - the `use` statements must be defined per file, see the [docs](https://www.php.net/manual/en/language.namespaces.importing.php#language.namespaces.importing.scope).

**Comment by TangRufus** [comment]
@chesio 

Nice touch about vlucas/phpdotenv v5!
Do you mind make a PR for it?

**Comment by chesio** [comment]
@TangRufus Sure, I'll try to get a PR ready over the coming weekend.

**Comment by koraysels** [comment]
SO how do we fix this ? I am stuck here aswell..

**Comment by Log1x** [comment]
> SO how do we fix this ? I am stuck here aswell..

- Run `composer require vlucas/phpdotenv:^5.2 oscarotero/env:^2.1`
- Update your `application.php` to reflect https://github.com/roots/bedrock/blob/master/config/application.php#L31
