### ISSUE TITLE
ABSPATH & Multiple Folder Paths conflict on WordPress.com, Pressable

### ISSUE THREAD

**Issue by JoshuaGoode** [roots/bedrock#560]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

I'm Joshua, a support engineer for Automattic. I focus primarily on WordPress.com and our hosted platform.

Recently, we were reviewing some errors related to some WordPress.com sites and found that multiple sites that used software from [https://roots.io](https://roots.io) were having issues due to an extra theme path set using ABSPATH.

We're not sure if this is a user configuration issue or if something that your tools add for your users.

Below, I cover what we found and some notes about ABSPATH on WordPress.com and Pressable.

#### Issue

We found that some site themes were constructed using tools that [https://roots.io/](https://roots.io/) provide.

It appears that something adds a mu-plugin to the sites called`register-theme-directory.php`.

On each site, this set an improper directory using ABSPATH.

In order to get some functions and features working properly on these sites we had to modify this file to find the directory properly.

We wanted to let you know in the event that this is something that your tools add for your users.

#### More on ABSPATH

We cover ABSPATH on WordPress.com a bit more at [https://wordpress.com/support/incompatible-plugins/#using-abspath-read-on](https://wordpress.com/support/incompatible-plugins/#using-abspath-read-on)

As mentioned, the plugin under `wp-content/mu-plugins/register-theme-directory.php` was incorrectly trying to set the default theme directory using ABSPATH.

On WordPress.com, the WordPress Core files are symbolically linked to another location on the platform. In other words, they are not in the site root, as is the case with a standard WordPress install. Due to this, using ABSPATH to locate files in the site can result in errors.

ABSPATH can be used when pointing to Core files, but it will not function correctly if used to locate files/folders within the `wp-content` directory.

For example, the following on WordPress.com will not work:

> if (!defined('WP\_DEFAULT\_THEME')) {  
>   
> register\_theme\_directory(ABSPATH . 'wp-content/themes');  
>   
> }

However, if it is necessary, it could be changed to:

> if (!defined('WP\_DEFAULT\_THEME')) {  
>   
> register\_theme\_directory(WP\_CONTENT\_DIR . '/themes');  
>   
> }

This is what was done in this situation. With WP\_CONTENT\_DIR, files/folders in the site root can be successfully accessed.

For more on ABSPATH, you may want to review one of Automattic's other partners at [https://pressable.com/knowledgebase/abspath-and-pressable/](https://pressable.com/knowledgebase/abspath-and-pressable/) for a more technical overview of properly using ABSPATH.

#### Issues & Questions

Let us know if you have any additional issues or questions. We'll be happy to help!

Feel free to reply here or use our contact form at [https://wordpress.com/support/developers/](https://wordpress.com/support/developers/)

Also, if your team needs a WordPress.com Business plan testing environment for testing your tools on, let me know! I'll see if we can coordinate that.

**Comment by swalkinshaw** [comment]
Thanks for the report.

Unfortunately it's not as simple as switching to `WP_CONTENT_DIR`. Bedrock points the content dir to `/app`:

https://github.com/roots/bedrock/blob/a3d36b26e8c784139fc68855d03c199647e78fec/config/application.php#L55-L56

This is not the same as `ABSPATH . 'wp-content/themes'` and would defeat the purpose of the mu-plugin. Here are the paths:
* `ABSPATH` => `/web/wp/wp-content/themes`
* `WP_CONTENT_DIR` => `/wep/app/themes`

The `ABSPATH` usage  is needed to get the location of the themes directory *included* in WP core (which gets installed by Composer) and not the site's actual content dir.

**Comment by retlehs** [comment]
> Below, I cover what we found and some notes about ABSPATH on WordPress.com and Pressable.

it seems like a WP site that was originally created with bedrock was migrated onto a platform where the bedrock structure is no longer used. in this case the `register-theme-directory.php` mu-plugin shouldn't be used anymore
