### ISSUE TITLE
Plugin activation / desactivation depending on environment

### ISSUE THREAD

**Issue by Androlax2** [roots/bedrock#571]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Would it be possible to disable/enable plugins depending on the environment?
But still leave room for the user to activate/delete plugins if the DISALLOW_FILE_MODS is not activated for example.
But put an error message if this is the case.

## Motivation

We could use this to be more efficient when moving from one environment to another, instead of doing everything by "hand".

## Additional context

Here is a repo that I found quite interesting, using YML to do this: https://github.com/PrimeTimeCode/wp-plugin-activation-manifest

**Comment by ethanclevenger91** [comment]
[Pertinent discussion here.](https://discourse.roots.io/t/how-can-i-disable-plugins-based-on-wp-env/9693/10)

**Comment by swalkinshaw** [comment]
https://github.com/lukasbesch/bedrock-plugin-disabler and https://github.com/PrimeTimeCode/wp-plugin-activation-manifest already exist. I haven't used them so I can't comment, but my position for now is this feature won't be built into Bedrock.
