### ISSUE TITLE
wp-sqlite-db does not work

### ISSUE THREAD

**Issue by SorinGFS** [roots/bedrock#580]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

wp-sqlite-db does not work with bedrock

## Motivation

wp-sqlite-db is not a theme or a plugin, it's a drop-in that allows wp to work with sqlite database making the whole installation portable. [Wp-sqlite-db ](https://github.com/aaemnnosttv/wp-sqlite-db) commes into scene before the database is created, and works in a manner that WP doesn't even know that the database is not mysql. I didn't study why it doesn't work, but it looks like some steps are missing in the installation process. Installation fails with error: `Warning: mysqli_real_connect(): (HY000/2002): No connection could be made because the target machine actively refused it.` ... of course, there is no mysql database installed on the system.

It would be disappointing to rule out the possibility to use sqlite as database....

## Additional context

bedrock version: 1.15.3
php version: 7.3.8

**Comment by swalkinshaw** [comment]
I thought we had something in our docs about this... but doesn't look like it 😔 

You're correct that Bedrock (due to Composer's feature set) doesn't support this automatically. https://github.com/Koodimonni/Composer-Dropin-Installer is a composer package which enables this though.

I actually just used it myself for wp-sqlite-db the other week and it worked fine.

**Comment by SorinGFS** [comment]
> I actually just used it myself for wp-sqlite-db the other week and it worked fine.

Thank you, I will try.

**Comment by SorinGFS** [comment]
> I actually just used it myself for wp-sqlite-db the other week and it worked fine.

I can't get it working! And I tried every possible combination, then I installed wp + wp-sqlite-db according their documentation in both provided ways, that installation works fine (without bedrock), and then... I also tried to manually copy the database folder plus `db.php` file in `wp-content` folder and tried to start `bedrock` in that way... also didn't work!

Are you sure that your install was able to access dashboard or you just tested in console?

**Comment by QWp6t** [comment]
Did you try `app/` or `web/app`? 🤔

**Comment by swalkinshaw** [comment]
```json
  "dropin-paths": {
    "web/app": ["package:aaemnnosttv/wp-sqlite-db:src/db.php"]
  },
```

This is what you want ^

**Comment by SorinGFS** [comment]
> This is what you want ^

Thank you both!
