### ISSUE TITLE
Maybe use a var for $webroot_dir 

### ISSUE THREAD

**Issue by skullwritter** [roots/bedrock#582]
* [x]  I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ ]  This request isn't a duplicate of an existing request
* [x]  This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community
## Summary
Maybe use a var in config/application.php for the webroot, the other was closed automatically by git #581 

## Motivation
https://github.com/roots/bedrock/blob/ea2872512b9cecb2dea2291ddabcb3693ee39d43/config/application.php#L26
In my case i change the web to public_html, for the php in vendor and configs and the env file to be completely secured.
The public_html is the public dir, below that there's no apparent way for a unknown user to access it, improving security.
my server example, can be replicated with:
- cPanel (normal) 
- Hestiacp (creating a specific config file to change the open_basedir to be equivalent to cpanel)
## Additional context

In my case i change the web to public_html, for the php in vendor and configs and the env file to be completely secured.
The public_html is the public dir, below that there's no apparent way for a unknown user to access it, improving security.
my server example, can be replicated with:
- cPanel (normal) 
- Hestiacp (creating a specific config file to change the open_basedir to be equivalent to cpanel)

possible code:
```

/**
 * Use Dotenv to set required environment variables and load .env file in root
 */
$dotenv = Dotenv\Dotenv::createUnsafeImmutable($root_dir);

if (file_exists($root_dir . '/.env')) {
    $dotenv->load();
    $dotenv->required(['WP_HOME', 'WP_SITEURL']);
    if (!env('DATABASE_URL')) {
        $dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD']);
    }
    /**
     * Document Root
     * Created from env var 'WP_WEBROOT'
     *
     * @var string
     */
    $webroot_dir = $root_dir . '/'. ltrim(env('WP_WEBROOT'),'/');
}
if(!isset($webroot_dir) || ($root_dir == rtrim($webroot_dir,'/')){
    /**
     * Document Root Fallback if it isn't created correctly
     * 
     * @var string
     */
    $webroot_dir = $root_dir . '/web';
}
```
The code was written on the fly, so it might contain errors.

**Comment by swalkinshaw** [comment]
env vars are meant for settings that change depending on the environment. For your use case, would you actually vary `WP_WEBROOT`?

**Comment by QWp6t** [comment]
I'm pretty sure you would not be able to change the document root in different environments because [it's hard-coded in composer.json](https://github.com/roots/bedrock/blob/master/composer.json#L53-L60).

**Comment by swalkinshaw** [comment]
Ah yes 👍 I'm going to close this then. Bedrock is meant as a boilerplate so feel free to customize `web` to whatever you want in your own version or fork.
