### ISSUE TITLE
Automatically translate WP and extensions

### ISSUE THREAD

**Issue by cedricDevWP** [roots/bedrock#583]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing request
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Hi,

I would like to know if it is possible to implement the functionality so that WP and extensions translate directly during a composer update?

## Motivation

Facilitate the update to avoid having to go back to the backoffice to perform the translation

Thx,
Cédric

**Comment by swalkinshaw** [comment]
Closing since this isn't related to Bedrock itself? Might be useful to discuss on our forums: https://discourse.roots.io/
