### ISSUE TITLE
.env.local failed to open stream php error when WP_ENV='development' and .env.local does not exist.

### ISSUE THREAD

**Issue by App1e5auce** [roots/bedrock#601]
Fresh bedrock install. 

When you only have .env (not .env.local) and your WP_ENV is set to development, WordPress admin will have an extra space at the top of the screen. This is caused by an invisible failed to open stream error when .env.local is not found.

To verify the cause, you can simply go into your application.php file and remove '.env.local' from the array on line 32. This removes php error, and the space at the top of WordPress admin.

**Comment by Furo42** [comment]
I can confirm this bug. The error is thrown also when WP_ENV variable is set to something else e.g. "production" or "staging".

**Comment by davideprevosto** [comment]
This is because the bedrock env example distributes is named as `.env.example` instead `.env.local`?

**Comment by mrgesco** [comment]
Proposed a PR for this #602

**Comment by TangRufus** [comment]
For reference: https://github.com/roots/bedrock/commit/b2781b890e5f988f847e716e6abbc48e34c3cc5c#commitcomment-54196503

**Comment by fab120** [comment]
I'm creating the pull request now :-)
