### ISSUE TITLE
Noob issue: .ENV configuration of WP URLs

### ISSUE THREAD

**Issue by cibulka** [roots/bedrock#64]
Hello everyone, as I am starting to get familiar with Bedrock, I am a little confused about setting the WP URLs in .ENV file. 

From ReadMe: 

> WP_HOME - Full URL to WordPress home (http://example.com)
> WP_SITEURL - Full URL to WordPress including subdirectory (http://example.com/wp)

The `index.php` (with `require '/wp/wp-blog-header.php'`) and `wp` folder (with "Wordpress stuff) lays under `web` folder, right? So it should be like this:

> WP_HOME - Full URL to WordPress home (http://example.com/web)
> WP_SITEURL - Full URL to WordPress including subdirectory (http://example.com/web/wp)

Setting "web" in URLs work for me (does not throw 404 errors on `http://example.com/wp/wp-admin` and actually displays something on `http://example.com`) but it's obviously not very pretty. 

So... Should I manually edit my .htaccess file? And sorry in advance, guys, I'm sure I'm missing something obvious. :) Thanks, P!

**Comment by meliaxford** [comment]
@cibulka thanks for the last link - saved me heaps of time.
