### ISSUE TITLE
Bug: htaccess not blocking /app request

### ISSUE THREAD

**Issue by D3vmotiv** [roots/bedrock#645]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
I created a bedrock projects and it all works fine for user routes. But my .htaccess taken from documenation is not blocking /app request or even /app/debug.log (or any file from web subdirectory), which i think should not be avaible for user.

#### Possible solutions
I could block this subdiretories in htaccess, but if i do that - my wordpress /uploads will stop working - so it's not solution

### Steps To Reproduce

My currently htaccess file:
```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
```

### Expected Behavior

redirect to frontpage.php or 404.php

### Actual Behavior

In most cases default hosting 404 or web file listing:

404
Not Found

The resource requested could not be found on this server!

### Versions

"roots/wordpress": "6.0.1",

**Comment by retlehs** [comment]
>  But my .htaccess taken from documenation is not blocking /app request or even /app/debug.log (or any file from web subdirectory), which i think should not be avaible for user.

the `web` directory must be public. it's up to you to lock down things further!

please join us over at https://discourse.roots.io/ if you have any other questions

**Comment by D3vmotiv** [comment]
Okey I see a world where its safe to dont protect that. But for example if user type /app/debug.log he get access to all raw paths which i think is 0% safe

**Comment by davideprevosto** [comment]
> Okey I see a world where its safe to dont protect that. But for example if user type /app/debug.log he get access to all raw paths which i think is 0% safe

It is unsafe. You must change your debug.log path and save it outside the DocumentRoot. Or you could restrict access to that file.

**Comment by D3vmotiv** [comment]
Okey, I hope it's only this one file which i found to be unsafe. Thanks for advice.
