### ISSUE TITLE
Bug: wordpress-no-content ignores wordpress-install-dir

### ISSUE THREAD

**Issue by drzraf** [roots/bedrock#660]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

I updated the Bedrock repository + `composer.json` and started using `wordpress-no-content` **but `web/wp` is not created**.

#### What have you tried?

The dozens of `composer install / update / rm -rf vendor web/wp / mkdir web/wp / composer require roots/wordpress-no-content`  combinations

#### What insights have you gained?

That composer is totally stubborn

#### Possible solutions

None, so far

#### Temporary workarounds

`mv vendor/roots/wordpress-no-content web/wp`

### Steps To Reproduce

1. git clone bedrock
1. tweak composer.json
1. composer update / install

### Expected Behavior

Install everything

### Actual Behavior

Creates `vendor/roots/wordpress-no-content` but omits `web/wp`

### Relevant Log Output

I've a patch applied to composer.json so that additional dependencies don't keep me (too much) from updating `composer.json`

```diff
diff --git a/composer.json b/composer.json
index 0e0236c..815b371 100644
--- a/composer.json
+++ b/composer.json
@@ -32,15 +32,16 @@
   ],
   "require": {
     "php": ">=7.4",
-    "composer/installers": "^2.2",
+    "composer/installers": "^1.9|^2.2",
     "vlucas/phpdotenv": "^5.5",
     "oscarotero/env": "^2.1",
     "roots/bedrock-autoloader": "^1.0",
     "roots/bedrock-disallow-indexing": "^2.0",
-    "roots/wordpress": "6.1.1",
+    "roots/wordpress-no-content": "^6.1.1",
     "roots/wp-config": "1.0.0",
     "roots/wp-password-bcrypt": "1.1.0",
-    "wpackagist-theme/twentytwentythree": "^1.0"
+    "wpackagist-theme/twentytwentythree": "^1.0",
+    "wikimedia/composer-merge-plugin": "^2.0.1"
   },
   "require-dev": {
     "squizlabs/php_codesniffer": "^3.7.1",
```

### Versions

1.21.1 (6cc8956)

**Comment by retlehs** [comment]
Hi there! The issues on this repo are meant for bug reports and not personal support requests

The standalone `roots/wordpress-no-content` package does not contain the `roots/wordpress-core-installer` package. Please create a topic on https://discourse.roots.io/ if you need further help.
