### ISSUE TITLE
Capistrano SQL backup and sync

### ISSUE THREAD

**Issue by guix77** [roots/bedrock#68]
Thanks for this wonderful project which really helped me reach new professional heights ! I started with the Roots base theme, then tried Bedrock with Composer only, then I went into Grunt, then Capistrano, and now I'm even managing my Drupal websites with Capistrano and Drush :)

I'd love to see SQL Capistrano tasks in Bedrock, and I know it's your TODO list, such as
- an automatic SQL backup of the old release each time we deploy (not to be included in rollbacks ; just in case, when WP needs to update its database)
- a manually invoked task : SQL sync from an environment to another, which needs also to update the wp_options table with the correct URLs depending on environments

**Comment by tommymarshall** [comment]
I added database backups when pushing/puling a DB. Great piece of mind. 

Added to `config/deploy.rb`:

```ruby
# The above update_option_paths task is not run by default
# Note that you need to have WP-CLI installed on your server
# Uncomment the following line to run it on deploys if needed
after 'deploy:publishing', 'deploy:update_option_paths'

time             = Time.new
backup_timestamp = time.strftime("%Y%m%d%H%M")

set :db_backup_file_name,        -> {"wpcli_db_backup.#{backup_timestamp}.sql.gz"}
set :local_db_folder_path,       -> {"./db_backups"}
set :local_db_folder_file_path,  -> {"./db_backups/#{fetch(:db_backup_file_name)}"}
set :remote_db_folder_path,      -> {"#{fetch(:deploy_to)}/db_backups"}
set :remote_db_folder_file_path, -> {"#{fetch(:deploy_to)}/db_backups/#{fetch(:db_backup_file_name)}"}

before 'wpcli:db:pull', :backup_local_db do
  run_locally do
    execute :mkdir, "-p", fetch(:local_db_folder_path)
    execute :wp, :db, :export, "- |", :gzip, ">", fetch(:local_db_folder_file_path)
  end
end

before 'wpcli:db:push', :backup_remote_db do
  on roles(:web) do
    within release_path do
      execute :mkdir, "-p", fetch(:remote_db_folder_path)
      execute :wp, :db, :export, "- |", :gzip, ">", fetch(:remote_db_folder_file_path)
    end
  end
end
```

And then just .gitignore the `db_backups` directory.
