### ISSUE TITLE
Wordpress Version in composer.json is ignored

### ISSUE THREAD

**Issue by worldwideweber** [roots/bedrock#684]
### Version

1.21.1

### What did you expect to happen?

I wont to downgrade the Wordpress Verison in composer.

### What actually happens?

 "roots/wordpress": "6.1" -> will install 6.3

### Steps to reproduce

Change Version in composer.json and update/install composer

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Please head on over to https://discourse.roots.io/ for support requests
