### ISSUE TITLE
There is no documentation on how to add custom blocks to a theme/plugin

### ISSUE THREAD

**Issue by cawa-93** [roots/bedrock#690]
### Summary

In our themes and plugins, we often create custom blocks for the Gutenberg editor. These blocks require [their own build process](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/). I really miss the documentation on how to integrate this with bedrock.

**Comment by retlehs** [comment]
Feel free to ask over at https://discourse.roots.io/ how folks in the community handle this kinda thing, but this is outside the scope of Bedrock's docs specifically
