### ISSUE TITLE
Cannot override eg. DISALLOW_FILE_MODS in .env??

### ISSUE THREAD

**Issue by winternet-studio** [roots/bedrock#700]
### Version

Where to find?! Installed Nov 14

### What did you expect to happen?

Setting DISALLOW_FILE_EDIT and DISALLOW_FILE_MODS to false in .env should allow installing plugins/themes even on production

### What actually happens?

Still cannot install plugins/themes

Dumped out self::$configMap in Config::apply() and both values are true - was expecting them to be false

Why can't one override those in .env? It would be logical that .env has the top priority...

### Steps to reproduce

Add to .env for production site:

DISALLOW_FILE_EDIT=false
DISALLOW_FILE_MODS=false

### Please confirm this isn't a support request.

Yes

**Comment by chesio** [comment]
@winternet-studio Bedrock philosophy is to rely on Composer for dependency management, therefore plugins and themes can be only installed via Composer. If you need to install plugins/themes via WordPress backend, you probably shouldn't be using Bedrock in the first place.

**Comment by winternet-studio** [comment]
> @winternet-studio Bedrock philosophy is to rely on Composer for dependency management, therefore plugins and themes can be only installed via Composer. If you need to install plugins/themes via WordPress backend, you probably shouldn't be using Bedrock in the first place.

I understand that but our client wants to have the option to install their own plugins - so only some plugins will be managed by composer. It's not our decision. But regardless, that is beside the point. The question is why doesn't .env have top priority...

**Comment by retlehs** [comment]
> Setting DISALLOW_FILE_EDIT and DISALLOW_FILE_MODS to false in .env should allow installing plugins/themes even on production

Bedrock's config isn't setup for this out of the box, but you're more than welcome to modify your install to work this way if that's what you'd like

Feel free to open a topic on https://discourse.roots.io/ if you have further questions
