### ISSUE TITLE
Redis Object Cache not working on WP_ENV='production'

### ISSUE THREAD

**Issue by 10corp** [roots/bedrock#702]
### Version

6.4.2

### What did you expect to happen?

Filesystem: Not writeable
Log:
Status: Connected
Client: PhpRedis (v5.3.4)
Drop-in: Valid
Disabled: No
Ping: 1
Errors: []
PhpRedis: 5.3.4
Relay: Not loaded
Predis: 2.1.2
Credis: Not loaded
PHP Version: 8.0.30
Plugin Version: 2.5.0
Redis Version: 6.0.16
Multisite: No
Metrics: Enabled
Metrics recorded: 4
Filesystem: File modifications are not allowed.

### What actually happens?

Redis Object Cache not working on WP_ENV='production'
Filesystem: File modifications are not allowed.
But WP_ENV='development' Works fine.

### Steps to reproduce

install bedrock and Redis Object Cache

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Head over to https://discourse.roots.io for support
