### ISSUE TITLE
[Feat] Also ignore env files not starting with `.env`

### ISSUE THREAD

**Issue by hirasso** [roots/bedrock#707]
### Summary

Hi there, I hope it's ok to open another issue right away. 

In Bedrock's `.gitignore`, would you be open to add a line to also ignore files _ending_ with `.env`? I think one line more wouldn't hurt to make sure no credentials make it into repos unnoticed.

```diff
 # Dotenv
 .env
 .env.*
+*.env
 !.env.example
```

### Additional context

I'm in the process of developing [wp-sync-deploy, a tool to deploy and sync WordPress sites between environments](https://github.com/hirasso/wp-sync-deploy). Right now, I've installed Bedrock to see how it goes with it's custom folder structure.

My tool makes use of a file `wp-sync-deploy.env` for configuration. I was unsure if I should call it `.env.wp-sync-deploy` instead, but ChatGPT said it didn't matter and was a matter of personal preference 😅

**Comment by retlehs** [comment]
That section of the gitignore is specifically for [Dotenv files](https://github.com/vlucas/phpdotenv)

Theres folks using files that end in `.env` that are committed to the repo on occasion. For example, I've come across several Lando setups that ship with a `.lando.env` file that is committed to the repo. This is something we do in Radicle as well.

**Comment by hirasso** [comment]
oh.. ok. Then I need to change wp-sync-deploy to follow that convention.
