### ISSUE TITLE
Add `WP_DISABLE_FATAL_ERROR_HANDLER=true` constant to development

### ISSUE THREAD

**Issue by strarsis** [roots/bedrock#711]
### Summary

WordPress automatically sends an admin email when a fatal PHP error is encountered.
However, this is usually not intended in development (it is very annoying/confusing actually).

Setting the `WP_DISABLE_FATAL_ERROR_HANDLER` constant to `true` prevents sending those WordPress admin error emails.
```php
Config::define('WP_DISABLE_FATAL_ERROR_HANDLER',true);
````

### Additional context

https://wordpress.stackexchange.com/a/361002/134384

**Comment by Tofandel** [comment]
https://github.com/roots/bedrock/blob/master/config/environments/development.php#L13
