### ISSUE TITLE
404 on all perm link on frontend

### ISSUE THREAD

**Issue by dedanirungu** [roots/bedrock#716]
### Version

1.24.0

### What did you expect to happen?

To see the page

### What actually happens?

I am getting error 404

### Steps to reproduce

Create an instance and open front end

### Please confirm this isn't a support request.

Yes, No

**Comment by retlehs** [comment]
Head on over to https://discourse.roots.io/ for support

I'd also suggest reading https://discourse.roots.io/t/how-to-best-ask-questions-on-this-forum/24582 — you will need to provide more details if you're looking for help
