### ISSUE TITLE
Seperate dynamic from static content for containerisation

### ISSUE THREAD

**Issue by tamis-laan** [roots/bedrock#723]
### Summary

I'm trying to containerize bedrock such that developers can develop themes and plugins for a specific customer website. I would like to separate static content from dynamic content. In other words I would like to build a docker image that contains the static code for plugins and themes while dynamic assets such as `/web/cache`, `/web/uploads` and plugins installed inside using the wordpres interface `/web/plugins` `web/mu-plugins` to be separated such that they can be hosted using on a volume.

The problem arises from the fact that a custom plugins are contained in the same directory as dynamically installed plugins i.e. `/web/plugins` and that the dynamic content is placed in different folders. It would be better if dynamic content would be placed into a folder such as `/web/app/dynamic`.

**Comment by Log1x** [comment]
This would best asked in a support request on [Discourse](https://discourse.roots.io/).
