### ISSUE TITLE
WP CLI occurs “Error establishing a database connection.” in Bedrock project

### ISSUE THREAD

**Issue by Sergey98Am** [roots/bedrock#724]
### Version

6.5.3

### What did you expect to happen?

It should added ThemeOptions with `wp` command

### What actually happens?

I use Bedrock and Sage with [Pantheon](https://pantheon.io/). I have installed WP CLI globally, but some commands do not work, for example `wp cache`, `wp cron`, `wp comment`…, it occurs `Error: Error establishing a database connection.`
In `.env` file db settings were these

```
DB_NAME='wordpress'
DB_USER='root'
DB_PASSWORD=
DB_HOST='database'
```

After searching this issue, I have changed `DB_HOST` from `database` to `localhost` and destroyed db using `lando destroy` command, but the result is the same. How can I fix this issue?

In addition, I want to use WP CLI for acf-composer package.

### Steps to reproduce

1. Add WordPress+Bedrock+Sage project on [Pantheon](https://pantheon.io/)
2. Install WP CLI globally
3. Clone repository from [Pantheon](https://pantheon.io/)
4. Add `.env` file
5. Init `lando` using pantheon in the current directory command
6. Start `lando`
7. Check `wp` commands

### Please confirm this isn't a support request.

No

**Comment by Sergey98Am** [comment]
Thank you @Log1x. I have created a [topic](https://discourse.roots.io/t/wp-cli-occurs-error-establishing-a-database-connection-in-bedrock-project/27200) already.

**Comment by Log1x** [comment]
That appears to be a link to a private message.

**Comment by Sergey98Am** [comment]
Sorry @Log1x. I thought that was a way to create a topic. Honestly, I cannot find a way to open a topic on roots. I'm opening a Topic, but I cannot create a topic.

![Screenshot from 2024-05-27 15-27-34 (1)](https://github.com/roots/bedrock/assets/52923458/43f08f59-e901-4e73-97bf-b7cd27732077)

 Can you tell me how to open a topic on roots, if it is not difficult?
