### ISSUE TITLE
DDEV installation wp-admin can't find themes or plugins

### ISSUE THREAD

**Issue by turnstylerj** [roots/bedrock#730]
### Version

6.5.5

### What did you expect to happen?

Themes and plugins are accessible in wp-admin control panel after installing Bedrock with DDEV.

### What actually happens?

Themes and plugins are not accessible in wp-admin control panel after installing Bedrock with DDEV.

### Steps to reproduce

1. Install Bedrock with DDEV according to the [docs](https://roots.io/bedrock/docs/bedrock-with-ddev/).
2. Access the WP control panel and go through the WP installation/user creation steps.
3. Install a plugin via composer as a test (i.e. `composer require wpackagist-plugin/advanced-custom-fields`)
4. In the control panel, go to Appearance > Themes (Error: The theme directory "twentytwentyfour" does not exist.)
5. In the control panel, go to Plugins > Installed Plugins ("No plugins are currently available." though plugin exists in /web/app/plugins).

### System info

macOS Sonoma 14.5

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Please use https://discourse.roots.io/ for support requests
