### ISSUE TITLE
Error establishing a database connection right after installation (at first click to login page)

### ISSUE THREAD

**Issue by belmaroc** [roots/bedrock#743]
### Version

1.25.0

### What did you expect to happen?

I expected to see the WP admin login page

### What actually happens?

I got the "Error establishing a database connection"

### Steps to reproduce

I installed bedrock via composer
I configured my .env file
![image](https://github.com/user-attachments/assets/1ab04c72-fd12-4ff5-9bfe-c10d71ec2611)

I went through the wordpress installation (choose language, then sitename, username, password and email)
![image](https://github.com/user-attachments/assets/5adafcea-5e22-4ba3-ab6e-fe3bca4226e4)

And at first try to log in I got the error
![image](https://github.com/user-attachments/assets/c3ed7c42-9fa9-4bb4-9fd6-2fbd947fa867)

I repeated the process almost 6 times.

### System info

Xampp for Windows 10 (22H2)
PHP 8.2.12
Apache/2.4.58 (Win64)
Database client version: libmysql - mysqlnd 8.2.12

### Please confirm this isn't a support request.

No

**Comment by retlehs** [comment]
Please head over to https://discourse.roots.io/ for support
