### ISSUE TITLE
REST API Issue in Bedrock 1.26.0 Affecting Site Health, REST API and Page Builders

### ISSUE THREAD

**Issue by digital-skylines** [roots/bedrock#753]
### Version

1.26.0

### What did you expect to happen?

Create a new project with a fresh install bedrock with my usual tools such as elementor or bricks builder.

### What actually happens?

In the “site health” menu, I come across this error, which is not present in other versions :
![Capture d’écran 2024-12-19 152500](https://github.com/user-attachments/assets/a22cebad-a86e-480b-92ab-6d38e4db5ee7)

When I try to open with elementor or bricks, this is the error I get
![Capture d’écran 2024-12-19 153132](https://github.com/user-attachments/assets/96383471-aea5-4033-8f29-dd89b95c0339)

I got the error in the “site health” section just after a standard installation, without doing anything more.

The issue doesn't seem to be specific to me, as it persists in the new 1.26.0 Bedrock version. For now, I’ve reverted to using 1.25.1 to avoid the problem. However, I wanted to bring this to your attention so it can be addressed in future updates, preventing any delays in discovering and resolving it.

Thanks for bedrock, it's a great tool that I've been using for a few months as a developer.

### Steps to reproduce

Install a new version in 1.26.0
Go to health care
Install elementor
Try to open a page with elementor.

 (I think that the problem is obviously with the REST API because bricks builder target the function wp_remote_post)

### System info

OS: Windows 11
Local Server: Laragon
PHP: 8.1.10
Apache: 2.4.62
MySQL: mysql-8.0.30

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
This isn't a Bedrock issue, and this issue does not exist in Bedrock

**Comment by digital-skylines** [comment]
Okay... I think you're wrong but that's not my business anymore, I've fulfill my duty, I'll continue using 1.25.1 until it works in newer versions.

**Comment by PincheWero** [comment]
This is absolutely a Bedrock issue. I've installed a completely fresh install (twice) same issue. No Bedrock? Clean as a whistle (same settings).

Something is messing with the REST API - database connection randomly gets lost as well.
