### ISSUE TITLE
WP-CLI & MAMP 3

### ISSUE THREAD

**Issue by joshmedeski** [roots/bedrock#93]
I just upgraded to MAMP v3 and I'm unable to get WP-CLI working. I'm getting this error 

```
Warning: mysql_connect(): No such file or directory in .../web/wp/wp-includes/wp-db.php on line 1372
```

Took a look at the file and couldn't figure out what went wrong. Thanks again for helping!

**Comment by nipun5perera** [comment]
I found that you can fix this issue by defining unix socket on .env file.

`DB_HOST='localhost:/Applications/MAMP/tmp/mysql/mysql.sock'`
