### ISSUE TITLE
Introduce SSL support

### ISSUE THREAD

**Issue by nathanielks** [roots/bedrock#99]
Hey all-

Was curious, with discussions over at [roots/bedrock-ansible](https://github.com/roots/bedrock-ansible) talking about introducing SSL support on that side, I wanted to get the conversation started on how to introduce SSL support on this side.

Is this something we'd want to include here and activate that functionality using a constant, or just allow the user to enable all that on their own?

**Comment by rstormsf** [comment]
I'm setting up SSL right now and would like to know if my plan is correct:
I'm going to follow these steps
https://rtcamp.com/wordpress-nginx/tutorials/ssl/thawte/
Can you guys confirm that I'm on the right track with these?
Should I add those lines:
```
define('FORCE_SSL_ADMIN', true);
define('FORCE_SSL_LOGIN', true);
add_filter('force_ssl' , '__return_true');
``` to `config/application.php` ? in my bedrock repo?

For bedrock-ansible I'm going to create new template.yml file in nginx role, add those config from [blog](https://rtcamp.com/wordpress-nginx/tutorials/ssl/thawte/)
and use rsync to upload my certs, gitignore them as well and store in secure place. 

Please let me know your thoughts and if I'm on the right track.

**Comment by swalkinshaw** [comment]
@rstormsf we recently moved roots.io to SSL and the only two configuration changes in WP we needed were:

```php
define('FORCE_SSL_ADMIN', true);
define('FORCE_SSL_LOGIN', true);
```

We don't have the filter and haven't see any issues. Wouldn't hurt to add it as well though just in case.

**Comment by QWp6t** [comment]
Nah, you can't add the filter to `application.php`. The `add_filter()` function doesn't yet exist at that point. lol

**Comment by swalkinshaw** [comment]
That filter doesn't even exist in WP (master) anyway.

**Comment by rstormsf** [comment]
@swalkinshaw @QWp6t thank you guys.

**Comment by sandrodz** [comment]
Thank you!

had same issue bedrock behind jwilder/nginx-proxy docker container with auto generated ssl was causing infinite redirect loop on wp-admin/wp-login

 http://trick77.com/2012/12/01/prevent-ssl-redirect-loop-using-wordpress-and-haproxy/ this resolved it.

**Comment by lpirola** [comment]
Fixed link: https://trick77.com/prevent-ssl-redirect-loop-using-wordpress-and-haproxy/
